### ISSUE TITLE
Strange instrumentation error with simple FiberSocketChannel example

### ISSUE THREAD

**Issue by io7m** [puniverse/quasar#101]
Hello.

The following code:

```
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.InetSocketAddress;
import java.nio.ByteBuffer;

import co.paralleluniverse.fibers.Fiber;
import co.paralleluniverse.fibers.SuspendExecution;
import co.paralleluniverse.fibers.io.FiberServerSocketChannel;
import co.paralleluniverse.fibers.io.FiberSocketChannel;

public final class TestFibers
{
  private static final class TestFiber extends Fiber<Void>
  {
    private static final long        serialVersionUID = 1L;
    private final FiberSocketChannel channel;

    public TestFiber(
      final FiberSocketChannel ch)
    {
      this.channel = ch;
    }

    private void writeRawData(
      final ByteBuffer data)
      throws UnsupportedEncodingException,
        IOException
    {
      final ByteBuffer size_buffer = ByteBuffer.allocate(4);
      size_buffer.rewind();
      size_buffer.putInt(0, (int) (data.capacity() & 0xffffffffL));

      while (size_buffer.hasRemaining()) {
        this.channel.write(size_buffer);
      }

      while (data.hasRemaining()) {
        this.channel.write(data);
      }
    }

    @Override protected Void run()
      throws SuspendExecution,
        InterruptedException
    {
      try {
        try {
          System.out.println("TestFiber: started for "
            + this.channel.getRemoteAddress());

          {
            final ByteBuffer b =
              ByteBuffer.wrap("HELLO\r\n".getBytes("UTF-8"));
            this.writeRawData(b);
          }

          for (;;) {
            final ByteBuffer buffer = ByteBuffer.allocate(1024);
            final int r = this.channel.read(buffer);
            if (r == -1) {
              break;
            }

            System.out.println("TestFiber: read: "
              + new String(buffer.array(), "UTF-8"));
          }

          return null;
        } finally {
          System.out.println("TestFiber: finished for "
            + this.channel.getRemoteAddress());
        }
      } catch (final IOException e) {
        e.printStackTrace();
      }

      return null;
    }
  }

  public static void main(
    final String args[])
    throws Exception
  {
    final Fiber<Void> k = new Fiber<Void>() {
      private static final long serialVersionUID = 1L;

      @Override protected Void run()
        throws SuspendExecution,
          InterruptedException
      {
        try {
          System.out.println("server: opening socket");
          final FiberServerSocketChannel s = FiberServerSocketChannel.open();
          System.out.println("server: binding");
          s.bind(new InetSocketAddress("127.0.0.1", 20000));
          System.out.println("server: accepting");

          for (;;) {
            final FiberSocketChannel ch = s.accept();
            System.out.println("server: client connected: " + ch);
            new TestFiber(ch).start();
          }
        } catch (final IOException e) {
          e.printStackTrace();
        }

        System.out.println("server: done");
        return null;
      }
    };

    System.out.println("main: starting");
    k.start();
    System.out.println("main: waiting");
    k.join();
  }
}
```

Gives the following output:

```
main: starting
main: waiting
server: opening socket
server: binding
server: accepting
server: client connected: co.paralleluniverse.fibers.io.AsyncFiberSocketChannel@2fd4fc58
TestFiber: started for /127.0.0.1:41156
TestFiber: finished for /127.0.0.1:41156
WARNING: Uninstrumented methods (marked '**') or call-sites (marked '!!') detected on the call stack: 
	at co.paralleluniverse.common.util.ExtendedStackTrace.here (ExtendedStackTrace.java:46)
	at co.paralleluniverse.fibers.Fiber.checkInstrumentation (Fiber.java:1613)
	at co.paralleluniverse.fibers.Fiber.verifySuspend (Fiber.java:1586)
	at co.paralleluniverse.fibers.FiberAsync.run (FiberAsync.java:118)
	at co.paralleluniverse.fibers.io.FiberAsyncIO.run (FiberAsyncIO.java:50) (optimized)
	at co.paralleluniverse.fibers.io.AsyncFiberSocketChannel.write (AsyncFiberSocketChannel.java:107)
	at co.paralleluniverse.fibers.io.AsyncFiberSocketChannel.write (AsyncFiberSocketChannel.java:156)
	at com.io7m.jnecto.tests.catalog.server.quasar.TestFibers$TestFiber.writeRawData(java.nio.ByteBuffer) (TestFibers.java:36) **
	at com.io7m.jnecto.tests.catalog.server.quasar.TestFibers$TestFiber.run (TestFibers.java:56) (optimized)
	at com.io7m.jnecto.tests.catalog.server.quasar.TestFibers$TestFiber.run (TestFibers.java:1) (optimized)
	at co.paralleluniverse.fibers.Fiber.run1 (Fiber.java:1014)
Exception in Fiber "fiber-10000002" If this exception looks strange, perhaps you've forgotten to instrument a blocking method. Run your program with -Dco.paralleluniverse.fibers.verifyInstrumentation to catch the culprit!
java.lang.NullPointerException
	at co.paralleluniverse.fibers.FiberAsync.run(FiberAsync.java:121)
	at co.paralleluniverse.fibers.io.FiberAsyncIO.run(FiberAsyncIO.java:50)
	at co.paralleluniverse.fibers.io.AsyncFiberSocketChannel.write(AsyncFiberSocketChannel.java:107)
	at co.paralleluniverse.fibers.io.AsyncFiberSocketChannel.write(AsyncFiberSocketChannel.java:156)
	at com.io7m.jnecto.tests.catalog.server.quasar.TestFibers$TestFiber.writeRawData(TestFibers.java:36)
	at com.io7m.jnecto.tests.catalog.server.quasar.TestFibers$TestFiber.run(TestFibers.java:56)
	at com.io7m.jnecto.tests.catalog.server.quasar.TestFibers$TestFiber.run(TestFibers.java:1)
WARNING: Uninstrumented methods (marked '**') or call-sites (marked '!!') detected on the call stack: 
	at co.paralleluniverse.fibers.FiberAsync.run (FiberAsync.java:121)
	at co.paralleluniverse.fibers.io.FiberAsyncIO.run (FiberAsyncIO.java:50) (optimized)
	at co.paralleluniverse.fibers.io.AsyncFiberSocketChannel.write (AsyncFiberSocketChannel.java:107)
	at co.paralleluniverse.fibers.io.AsyncFiberSocketChannel.write (AsyncFiberSocketChannel.java:156)
	at com.io7m.jnecto.tests.catalog.server.quasar.TestFibers$TestFiber.writeRawData(java.nio.ByteBuffer) (TestFibers.java:36) **
	at com.io7m.jnecto.tests.catalog.server.quasar.TestFibers$TestFiber.run (TestFibers.java:56) (optimized)
	at com.io7m.jnecto.tests.catalog.server.quasar.TestFibers$TestFiber.run (TestFibers.java:1) (optimized)
	at co.paralleluniverse.fibers.Fiber.run1 (Fiber.java:1014)
Exception in Fiber "fiber-10000002" If this exception looks strange, perhaps you've forgotten to instrument a blocking method. Run your program with -Dco.paralleluniverse.fibers.verifyInstrumentation to catch the culprit!
java.lang.NullPointerException
	at co.paralleluniverse.fibers.FiberAsync.run(FiberAsync.java:121)
	at co.paralleluniverse.fibers.io.FiberAsyncIO.run(FiberAsyncIO.java:50)
	at co.paralleluniverse.fibers.io.AsyncFiberSocketChannel.write(AsyncFiberSocketChannel.java:107)
	at co.paralleluniverse.fibers.io.AsyncFiberSocketChannel.write(AsyncFiberSocketChannel.java:156)
	at com.io7m.jnecto.tests.catalog.server.quasar.TestFibers$TestFiber.writeRawData(TestFibers.java:36)
	at com.io7m.jnecto.tests.catalog.server.quasar.TestFibers$TestFiber.run(TestFibers.java:56)
	at com.io7m.jnecto.tests.catalog.server.quasar.TestFibers$TestFiber.run(TestFibers.java:1)
WARNING: Uninstrumented methods (marked '**') or call-sites (marked '!!') detected on the call stack: 
	at co.paralleluniverse.fibers.FiberAsync.run (FiberAsync.java:121)
	at co.paralleluniverse.fibers.io.FiberAsyncIO.run (FiberAsyncIO.java:50) (optimized)
	at co.paralleluniverse.fibers.io.AsyncFiberSocketChannel.write (AsyncFiberSocketChannel.java:107)
	at co.paralleluniverse.fibers.io.AsyncFiberSocketChannel.write (AsyncFiberSocketChannel.java:156)
	at com.io7m.jnecto.tests.catalog.server.quasar.TestFibers$TestFiber.writeRawData(java.nio.ByteBuffer) (TestFibers.java:36) **
	at com.io7m.jnecto.tests.catalog.server.quasar.TestFibers$TestFiber.run (TestFibers.java:56) (optimized)
	at com.io7m.jnecto.tests.catalog.server.quasar.TestFibers$TestFiber.run (TestFibers.java:1) (optimized)
	at co.paralleluniverse.fibers.Fiber.run1 (Fiber.java:1014)
```

I'm using the instrumentation agent at run-time with `-javaagent:quasar-core-0.7.2.jar -Dco.paralleluniverse.fibers.verifyInstrumentation`. It's not clear to me why that method would be uninstrumented, and that `NullPointerException` looks bad...

This is using `quasar-core-0.7.2` from Maven Central, and:

```
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (Arch Linux build 7.u79_2.5.5-1-x86_64)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
```

**Comment by pron** [comment]
As the exception suggests, there are uninstrumented methods, in your case `writeRawData`. Add `@Suspendable` or `throw SuspendExecution` to `writeRawData`.

**Comment by io7m** [comment]
Ah, that works, but it's a fairly unpleasant issue. This code is a simplification of a real program where `writeRawData` was actually defined in a completely different package that knows nothing about `quasar`. I can't annotate it or change the exceptions it throws (I don't control the package and even if I did, it would be inappropriate for it to have a dependency on `quasar`).

Is there another way around the problem?

**Comment by pron** [comment]
Yes. Two options:

1. Put the line  `com.acme.Foo.writeRawData` in a file called `META-INF/suspendables`
2. Turn on [automatic instrumentation](http://docs.paralleluniverse.co/quasar/#automatic-instrumentation)

The first option is preferable if you know that the number of methods you’ll need to list is small, or well-known to you. Note that uninstrumented methods will be marked with `**` in the warning following any report of an unexpected exception.

BTW, all of this will be made completely transparent (no need to annotate suspendable methods in any way) in Java 9.

**Comment by io7m** [comment]
Thanks, I'll try it.

> BTW, all of this will be made completely transparent (no need to annotate suspendable methods in any way) in Java 9.

Is there a JSR or something about this that I can read? I'm curious!

**Comment by pron** [comment]
Not yet. We’ll announce the details once they’ve been finalized.

**Comment by io7m** [comment]
Somewhat redundant then, given that they may stop being necessary soon, but it would be nice if the annotations were available in a separate JAR file (similar to pure annotations packages such as the `jsr-305` jar that seems to crop up everywhere) so that packages could be annotated without necessarily pulling in all of `quasar`.

**Comment by io7m** [comment]
Thanks for the quick response!

**Comment by pron** [comment]
> This way, packages could be annotated without necessarily pulling in all of quasar.

That is already the case. Quasar is only required for compilation in that scenario. If Quasar is not available at runtime, the annotation class won't be resolved. Annotation classes that cannot be resolved at runtime are ignored.
