### ISSUE TITLE
Instrumentation failure when wrapping a fiber-unaware interface

### ISSUE THREAD

**Issue by io7m** [puniverse/quasar#103]
Apologies for the size of the source, but the vast majority of the classes are empty stubs as this code is extracted from a real project in order to attempt to track down a `NullPointerException` inside `quasar`. The actual classes of interest are the `ClientFiber` and `FiberBlockingClientInitial` classes:

https://github.com/io7m/quasar-npe-20150705_0000

Please run the `ServerMainPlain` class, which will bind a server to `127.0.0.1:20000`. Connecting to the server with `$ nc -vvv 127.0.0.1 20000` results in:

```
15:26:10.699 [ForkJoinPool-default-fiber-pool-worker-3] DEBUG c.i.q.ServerPlain[/127.0.0.1:20000] - starting
15:26:10.699 [ForkJoinPool-default-fiber-pool-worker-5] DEBUG c.i.q.ServerPlainMain - waiting for server start signal
15:26:10.707 [ForkJoinPool-default-fiber-pool-worker-3] DEBUG c.i.q.ServerPlain[/127.0.0.1:20000] - opening socket
15:26:10.786 [ForkJoinPool-default-fiber-pool-worker-3] DEBUG c.i.q.ServerPlain[/127.0.0.1:20000] - binding
15:26:10.787 [ForkJoinPool-default-fiber-pool-worker-3] DEBUG c.i.q.ServerPlain[/127.0.0.1:20000] - accepting
15:26:10.794 [ForkJoinPool-default-fiber-pool-worker-5] DEBUG c.i.q.ServerPlainMain - started server
15:26:10.795 [ForkJoinPool-default-fiber-pool-worker-5] DEBUG c.i.q.ServerPlainMain - waiting for server to stop
15:26:13.562 [ForkJoinPool-default-fiber-pool-worker-5] DEBUG c.i.q.ServerPlain[/127.0.0.1:20000] - client /127.0.0.1:42157 connected
15:26:13.596 [ForkJoinPool-default-fiber-pool-worker-3] DEBUG c.i.q.C.0.0.1.0.0.1:42157] - starting
WARNING: Uninstrumented methods (marked '**') or call-sites (marked '!!') detected on the call stack: 
	at co.paralleluniverse.common.util.ExtendedStackTrace.here (ExtendedStackTrace.java:46)
	at co.paralleluniverse.fibers.Fiber.checkInstrumentation (Fiber.java:1613)
	at co.paralleluniverse.fibers.Fiber.verifySuspend (Fiber.java:1586)
	at co.paralleluniverse.fibers.FiberAsync.run (FiberAsync.java:118)
	at com.io7m.quasar_npe_20150705_0000.FiberBlockingClientInitial.onCommandHelloAnonymous (FiberBlockingClientInitial.java:113)
	at com.io7m.quasar_npe_20150705_0000.ClientFiber.onHelloAnonymous(com.io7m.quasar_npe_20150705_0000.NectoCatalogMessageChannelWriter,com.io7m.quasar_npe_20150705_0000.NectoCatalogMessageChannelReader) (ClientFiber.java:94) **
	at com.io7m.quasar_npe_20150705_0000.ClientFiber.startHello (ClientFiber.java:143)
	at com.io7m.quasar_npe_20150705_0000.ClientFiber.run (ClientFiber.java:127)
	at com.io7m.quasar_npe_20150705_0000.ClientFiber.run (ClientFiber.java:1) (optimized)
	at co.paralleluniverse.fibers.Fiber.run1 (Fiber.java:1014)
WARNING: Uninstrumented methods (marked '**') or call-sites (marked '!!') detected on the call stack: 
	at co.paralleluniverse.common.util.ExtendedStackTrace.here (ExtendedStackTrace.java:46)
	at co.paralleluniverse.fibers.Fiber.checkInstrumentation (Fiber.java:1613)
	at co.paralleluniverse.fibers.Fiber.verifySuspend (Fiber.java:1586)
	at co.paralleluniverse.fibers.Fiber.verifySuspend (Fiber.java:1581)
	at co.paralleluniverse.fibers.Fiber.park (Fiber.java:582)
	at co.paralleluniverse.fibers.Fiber.park (Fiber.java:586)
	at co.paralleluniverse.fibers.FiberAsync.run (FiberAsync.java:121)
	at com.io7m.quasar_npe_20150705_0000.FiberBlockingClientInitial.onCommandHelloAnonymous (FiberBlockingClientInitial.java:113)
	at com.io7m.quasar_npe_20150705_0000.ClientFiber.onHelloAnonymous(com.io7m.quasar_npe_20150705_0000.NectoCatalogMessageChannelWriter,com.io7m.quasar_npe_20150705_0000.NectoCatalogMessageChannelReader) (ClientFiber.java:94) **
	at com.io7m.quasar_npe_20150705_0000.ClientFiber.startHello (ClientFiber.java:143)
	at com.io7m.quasar_npe_20150705_0000.ClientFiber.run (ClientFiber.java:127)
	at com.io7m.quasar_npe_20150705_0000.ClientFiber.run (ClientFiber.java:1) (optimized)
	at co.paralleluniverse.fibers.Fiber.run1 (Fiber.java:1014)
WARNING: Uninstrumented methods (marked '**') or call-sites (marked '!!') detected on the call stack: 
	at co.paralleluniverse.common.util.ExtendedStackTrace.here (ExtendedStackTrace.java:46)
	at co.paralleluniverse.fibers.Fiber.checkInstrumentation (Fiber.java:1613)
	at co.paralleluniverse.fibers.Fiber.verifySuspend (Fiber.java:1586)
	at co.paralleluniverse.fibers.Stack.popMethod (Stack.java:155)
	at co.paralleluniverse.fibers.FiberAsync.run (FiberAsync.java:152)
	at com.io7m.quasar_npe_20150705_0000.FiberBlockingClientInitial.onCommandHelloAnonymous (FiberBlockingClientInitial.java:113)
	at com.io7m.quasar_npe_20150705_0000.ClientFiber.onHelloAnonymous(com.io7m.quasar_npe_20150705_0000.NectoCatalogMessageChannelWriter,com.io7m.quasar_npe_20150705_0000.NectoCatalogMessageChannelReader) (ClientFiber.java:94) **
	at com.io7m.quasar_npe_20150705_0000.ClientFiber.startHello (ClientFiber.java:143)
	at com.io7m.quasar_npe_20150705_0000.ClientFiber.run (ClientFiber.java:127)
	at com.io7m.quasar_npe_20150705_0000.ClientFiber.run (ClientFiber.java:1) (optimized)
	at co.paralleluniverse.fibers.Fiber.run1 (Fiber.java:1014)
15:26:13.673 [ForkJoinPool-default-fiber-pool-worker-3] DEBUG c.i.q.C.0.0.1.0.0.1:42157] - completing
15:26:13.673 [ForkJoinPool-default-fiber-pool-worker-3] DEBUG c.i.q.C.0.0.1.0.0.1:42157] - closing channel
```

As can be seen, the `FiberBlockingClientInitial` class implements `NectoCatalogServerClientInitialType` and wraps an existing implementation to provide a fiber-blocking interface (the original implementation of `NectoCatalogServerClientInitialType` is unaware that `quasar` even exists). The methods in `FiberBlockingClientInitial` seem to be correctly annotated with `@Suspendable` as far as I can tell.

Interestingly, the `NullPointerException` I'm trying to track down occurs at
`co.paralleluniverse.fibers.FiberAsync.run (FiberAsync.java:121)` in the real project, which is the same location referenced here.

**Comment by circlespainter** [comment]
Try adding a `com.io7m.quasar_npe_20150705_0000.NectoCatalogServerClientInitialType.onCommandHelloAnonymous` line to a new `META-INF/suspendable-supers` resource and let me know.

Quasar needs needs to instrument all call sites to (potentially) suspendable methods for fiber suspension to work and if a suspendable method contains no such call sites then it is not instrumented at all.
In order to recognise a call site's target method as (potentially) suspendable, the latter must be currently marked as such and this rule does not spare abstract nor interface methods.

Your abstract `com.io7m.quasar_npe_20150705_0000.NectoCatalogServerClientInitialType.onCommandHelloAnonymous` method instead doesn't seem marked as suspendable in any way: nor through an annotation, nor through throws clauses, nor through `suspendable-supers`. This means that Quasar won't recognise the call site to a (potentially) suspendable method and won't instrument it. Since it seems to be the only call site of such kind in the `com.io7m.quasar_npe_20150705_0000.ClientFiber.onHelloAnonymous` method, the latter won't be instrumented at all and that's (probably) why you see it marked as non instrumented in the verification call stack.

[This](http://docs.paralleluniverse.co/quasar/#advanced-fibers) can shed more light on the subject.

**Comment by io7m** [comment]
> Your abstract com.io7m.quasar_npe_20150705_0000.NectoCatalogServerClientInitialType.onCommandHelloAnonymous method instead doesn't seem marked as suspendable in any way: nor through an annotation, nor through throws clauses, nor through suspendable-supers. 

Ah, right. I misunderstood the linked documentation. The interface methods must be added to `suspendable-supers` because the interface is fiber-unaware and the agent won't find the suspendable implementation.

**Comment by circlespainter** [comment]
You can also use automatic instrumentation to build such file (same docs section).

**Comment by io7m** [comment]
What is the correct way to run this from Ant? I don't use Gradle. The following build file (where "..." is the long omitted classpath required to pick up all of the dependencies):

```
<project>
  <taskdef
    name="scanSuspendables"
    classname="co.paralleluniverse.fibers.instrument.SuspendablesScanner"
    classpath="..."/>
  <target name="scan">
    <scanSuspendables
      auto="true"
      suspendablesFile="src/main/resources/META-INF/suspendables"
      supersFile="src/main/resources/META-INF/suspendables-supers">
      <fileset>
        <include name="target/classes/**"/>
      </fileset>
    </scanSuspendables>
  </target>
</project>
```

... results in:

```
$ ant -f instrument.xml scan
Buildfile: /home/someone/fossil/com.io7m/io7m-jnecto/io7m-jnecto-catalog-server-quasar/instrument.xml

scan:
[scanSuspendables] null

BUILD FAILED
/home/someone/fossil/com.io7m/io7m-jnecto/io7m-jnecto-catalog-server-quasar/instrument.xml:11: java.lang.NullPointerException
	at co.paralleluniverse.fibers.instrument.SuspendablesScanner.run(SuspendablesScanner.java:168)
	at co.paralleluniverse.fibers.instrument.SuspendablesScanner.execute(SuspendablesScanner.java:134)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:853)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
```

**Comment by circlespainter** [comment]
You can execute easily Ant tasks from Maven too, an example can be found in the [`quasar-mvn-archetype` project here](https://github.com/puniverse/quasar-mvn-archetype/blob/master/src/main/resources/archetype-resources/pom.xml#L104). That's an invocation to the instrumentation task but you can easily use it as a template and change it the suspendables scanner one.
