### ISSUE TITLE
VerifyInstrumentation did not catch lambda implementing a @Suspendable interface method

### ISSUE THREAD

**Issue by mstanescu** [puniverse/quasar#137]
I am running with quasar 0.7.2

Take the following code
```
public abstract class ServiceHandler 
{
    public interface HandlerWithException<E>
    {
        @Suspendable
        void handle(E event) throws Exception;
    }
    @Suspendable
    protected void executeWithEvent(HandlerWithException<Integer> handler) throws Exception
    {
          handler.handle(0);
    }
}

// later on when using

executeWithConnection((Integer event)->
            {
                  // park fiber here 
                  // park
                  // park ->NullPointerException
            }
```

At some point this throws a NullPointerException in Fiber.park. 

After some hours of brain damage was solved after changing the interface to the following:
```
    public interface HandlerWithException<E>
    {
        void handle(E event) throws Exception, SuspendExecution;
    }
```

I would have expected that the verifyInstrumentation would catch this. 

Regards

**Comment by circlespainter** [comment]
So strange, 0.7.2 includes better instrumentation verification _and_ support for `@Suspendable` on individual interface methods. Same issue with 0.7.3?

**Comment by circlespainter** [comment]
Ok, I think I got a better grasp and it happens even with Quasar 0.7.3+: the `@Suspendable` annotation marks the interface as a potentially suspendable call site but it doesn't mark as suspendable all the implementations (and rightly so as there could be some that are suspendable and some not suspendable).
On the other hand the `throws SuspendExecution` of course does it for both the interface and the implementation. It looks like there's [no way to annotate a lambda in Java 8](http://stackoverflow.com/questions/22375891/annotating-the-functional-interface-of-a-lambda-expression) (unless I overlooked) so if you want to use `@Suspendable` you need to use an anonymous class as an implementation, else you can use `throws SuspendExecution` and it'll work anyway.

As for verification in the `@Suspendable` case it works for me with 0.7.3 because when running `gradle test` on [this project](https://github.com/circlespainter/quasar-137) it correctly tells that there's instrumentation missing:

```
Exception in Fiber "fiber-10000001" java.lang.RuntimeException: co.paralleluniverse.fibers.VerifyInstrumentationException: Uninstrumented methods (marked '**') or call-sites (marked '!!') detected on the call stack: 
	at co.paralleluniverse.common.util.ExtendedStackTrace.here (ExtendedStackTrace.java:44 bci: 8)
	at co.paralleluniverse.fibers.Fiber.checkInstrumentation (Fiber.java:1618 bci: 0)
	at co.paralleluniverse.fibers.Fiber.verifySuspend (Fiber.java:1591 bci: 6)
	at co.paralleluniverse.fibers.Fiber.verifySuspend (Fiber.java:1586 bci: 3)
	at co.paralleluniverse.fibers.Fiber.sleep (Fiber.java:635 bci: 0)
	at co.paralleluniverse.fibers.Fiber.sleep (Fiber.java:627 bci: 4)
	at testgrp.Quasar137.lambda$null$0(java.lang.Integer) (Quasar137.java:36 bci: 11) **
	at testgrp.Quasar137$ServiceHandler.executeWithEvent (Quasar137.java:23 bci: 105)
	at testgrp.Quasar137.lambda$doAll$b00dfab3$1 (Quasar137.java:34 bci: 97)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run (SuspendableUtils.java:44 bci: 4)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run (SuspendableUtils.java:32 bci: 1)
	at co.paralleluniverse.fibers.Fiber.run (Fiber.java:1024 bci: 11)
	at co.paralleluniverse.fibers.Fiber.run1 (Fiber.java:1019 bci: 1)
	at testgrp.Quasar137.lambda$doAll$b00dfab3$1(Quasar137.java:40)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:44)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:32)
	at co.paralleluniverse.fibers.Fiber.run(Fiber.java:1024)
```

Isn't it the case for you?

**Comment by mstanescu** [comment]
Thanks for the effort. I forked your project and indeed with 0.7.3 there is
an exception but if you change dependency to use 0.7.2 there is no
exception. Everything just "works"

:test
Running test: Test test(testgrp.Quasar137Test)
file://D:\Downloads\quasar-137-master\build\reports\tests/index.html
:check
:build

I will upgrade my project dependency to quasar 0.7.3.

With 0.7.2 i would say is non-deterministic. In my real project i used to
get a NullPointerException from inside Fiber.park after the 3rd time when i
parked the fiber.

Anyway. I'm glad to find out everything is good.
