### ISSUE TITLE
SuspendablesScanner Ant check fails from maven plugin

### ISSUE THREAD

**Issue by ShibaBandit** [puniverse/quasar#138]
In the SuspendablesScanner constructor, it sets 

```java
this.ant = getClass().getClassLoader() instanceof AntClassLoader;
```

This check fails when using the [Maven Ant Run Plugin](https://maven.apache.org/plugins/maven-antrun-plugin/).

Resulting in stack trace:

```stacktrace
Caused by: org.apache.maven.plugin.MojoExecutionException: An Ant BuildException has occured: java.lang.NullPointerException
around Ant part ...<scanSuspendables auto="false" suspendablesFile="target/resources/META-INF/suspendables">... @ 6:92 in /Users/nhunter/github/aws-sdk-java/aws-java-sdk-core/target/antrun/build-main.xml
	at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:342)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 25 more
Caused by: /Users/.../github/aws-sdk-java/aws-java-sdk-core/target/antrun/build-main.xml:6: java.lang.NullPointerException
	at co.paralleluniverse.fibers.instrument.SuspendablesScanner.execute(SuspendablesScanner.java:154)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:313)
	... 27 more
Caused by: java.lang.NullPointerException
	at co.paralleluniverse.fibers.instrument.SuspendablesScanner.run(SuspendablesScanner.java:182)
	at co.paralleluniverse.fibers.instrument.SuspendablesScanner.execute(SuspendablesScanner.java:134)
	... 39 more
```

Null pointer here:

```java
pus.add(projectDir.toUri().toURL());
```

Example Maven XML:

```xml
      <plugin>
        <artifactId>maven-antrun-plugin</artifactId>
        <version>1.8</version>
        <executions>
          <execution>
            <id>instrument-suspendables</id>
            <phase>compile</phase>
            <configuration>
              <target>
                  <taskdef name="scanSuspendables"
                           classname="co.paralleluniverse.fibers.instrument.SuspendablesScanner"/>
                  <scanSuspendables auto="false"
                                    suspendablesFile="target/resources/META-INF/suspendables">
                  </scanSuspendables>
              </target>
            </configuration>
            <goals>
              <goal>run</goal>
            </goals>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>co.paralleluniverse</groupId>
            <artifactId>quasar-core</artifactId>
            <version>0.7.3</version>
          </dependency>
        </dependencies>
      </plugin>
```

One quick fix may be to just allow the caller to set the 'ant' flag to true, overriding the check.

**Comment by circlespainter** [comment]
I must be missing something but I can't reproduce it [here](https://github.com/circlespainter/quasar-138/blob/master/pom.xml#L52). Is that example correct in order to reproduce the exception?

**Comment by circlespainter** [comment]
@ShibaBandit Closing soon for inactivity (but you can always reopen when you get more insight).

**Comment by ShibaBandit** [comment]
Thank you for your response. I've more or less copied your example to double check, but no luck. The only difference I can think of is that my project is a multi-module maven project (I've been playing around with hacking Quasar into the AWS Java SDK). However, I ended up manually going through the core and S3 libraries and swapping out their http client with comsat-http and just bubbling up the SuspendExection throws. Sort of a work in progress. I'll go ahead and close the issue.
