### ISSUE TITLE
ArrayIndexOutOfBoundsException during instrumentation

### ISSUE THREAD

**Issue by pniederw** [puniverse/quasar#164]
Oracle JDK 1.8.0_72, Mac OS 10.11, Kotlin 1.0, Quasar 0.7.5-20160215.165108-1

```
[quasar] ERROR: Unable to instrument class XXX$YYY$instance$2
java.lang.ArrayIndexOutOfBoundsException: -1
	at co.paralleluniverse.asm.Frame.a(Unknown Source)
	at co.paralleluniverse.asm.MethodWriter.visitMaxs(Unknown Source)
	at co.paralleluniverse.fibers.instrument.InstrumentMethod.accept(InstrumentMethod.java:530)
	at co.paralleluniverse.fibers.instrument.InstrumentClass.visitEnd(InstrumentClass.java:265)
	at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
	at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
	at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:113)
	at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:87)
	at co.paralleluniverse.fibers.instrument.JavaAgent$Transformer.transform(JavaAgent.java:185)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ...
```

**Comment by circlespainter** [comment]
Can you provide the code that triggers the error?

**Comment by pniederw** [comment]
Unfortunately I can't. I hoped that reporting this might be useful nevertheless.

**Comment by pron** [comment]
Can you try to reproduce it with different code?

**Comment by julianrz** [comment]
Any chance this is older asm version examining code containing Java8 features?

**Comment by circlespainter** [comment]
@julianrz Quasar uses ASM 5.0.4 and ASM supports Java 8 since 5.0 so this is not the case. It could be a bug indeed, perhaps even an ASM one, but it's difficult to tell without being able to reproduce the issue.

**Comment by karindoy** [comment]
i had this problem and find the problem, my class had a 
@InitiatingFlow
@StartableByRPC

but the class had 2 @Suspendable functions
