### ISSUE TITLE
Failing suspendable lambda case

### ISSUE THREAD

**Issue by circlespainter** [puniverse/quasar#168]
The following test case:

``` java
public class LambdaTest {
    @Suspendable
    @FunctionalInterface
    private interface I {
        @Suspendable
        void doIt();
    }

    private void run(I i) throws ExecutionException, InterruptedException {
        new Fiber() {
            @Override
            protected Object run() throws SuspendExecution, InterruptedException {
                i.doIt();
                return null;
            }
        }.start().join();
    }

    @Test
    public void lambda() throws Exception {
        run(() -> {
            try {
                Strand.sleep(10);
            } catch (final SuspendExecution e) {
                throw new AssertionError(e);
            } catch (final InterruptedException e) {
                throw new RuntimeException(e);
            }
        });
    }
}
```

Produces:

```
Caused by: co.paralleluniverse.fibers.VerifyInstrumentationException: Uninstrumented methods (marked '**') or call-sites (marked '!!') detected on the call stack: 
	at co.paralleluniverse.common.util.ExtendedStackTrace.here (ExtendedStackTrace.java:44 bci: 8)
	at co.paralleluniverse.fibers.Fiber.checkInstrumentation (Fiber.java:1621 bci: 0)
	at co.paralleluniverse.fibers.Fiber.verifySuspend (Fiber.java:1594 bci: 6)
	at co.paralleluniverse.fibers.Fiber.verifySuspend (Fiber.java:1589 bci: 3)
	at co.paralleluniverse.fibers.Fiber.sleep (Fiber.java:637 bci: 0)
	at co.paralleluniverse.fibers.Fiber.sleep (Fiber.java:629 bci: 4)
	at co.paralleluniverse.strands.Strand.sleep(long) (Strand.java:384 bci: 90)
	at co.paralleluniverse.fibers.lambdas.LambdaTest.lambda$lambda$0) (LambdaTest.java:50 bci: 3) **
	at co.paralleluniverse.fibers.lambdas.LambdaTest$1.run (LambdaTest.java:40 bci: 76)
	at co.paralleluniverse.fibers.Fiber.run (Fiber.java:1027 bci: 11)
	at co.paralleluniverse.fibers.Fiber.run1 (Fiber.java:1022 bci: 1)
	at co.paralleluniverse.fibers.Fiber.checkInstrumentation(Fiber.java:1672)
	at co.paralleluniverse.fibers.Fiber.checkInstrumentation(Fiber.java:1621)
	at co.paralleluniverse.fibers.Fiber.verifySuspend(Fiber.java:1594)
	at co.paralleluniverse.fibers.Fiber.verifySuspend(Fiber.java:1589)
	at co.paralleluniverse.fibers.Fiber.sleep(Fiber.java:637)
	at co.paralleluniverse.fibers.Fiber.sleep(Fiber.java:629)
	at co.paralleluniverse.strands.Strand.sleep(Strand.java:384)
	at co.paralleluniverse.fibers.lambdas.LambdaTest.lambda$lambda$0(LambdaTest.java:50)
	at co.paralleluniverse.fibers.lambdas.LambdaTest$1.run(LambdaTest.java:40)
	at co.paralleluniverse.fibers.Fiber.run(Fiber.java:1027)
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1022)
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:732)
	at co.paralleluniverse.fibers.FiberForkJoinScheduler$FiberForkJoinTask.exec1(FiberForkJoinScheduler.java:265)
	at co.paralleluniverse.concurrent.forkjoin.ParkableForkJoinTask.doExec(ParkableForkJoinTask.java:116)
	at co.paralleluniverse.concurrent.forkjoin.ParkableForkJoinTask.exec(ParkableForkJoinTask.java:73)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

A similar instrumentation verification exception can is produced by using `new Fiber(new SuspendableCallable() { ... })` and `new Fiber(() -> i.doIt())` as well.

**Comment by circlespainter** [comment]
Originated from https://groups.google.com/forum/#!topic/quasar-pulsar-user/DfdzqYeTFM8

**Comment by circlespainter** [comment]
Temporary workaround: use class rather than lambda.

**Comment by exFalso** [comment]
This now causes *all* lambdas to be instrumented, even when they are in a completely unrelated part of the codebase that will never ever suspend.

**Comment by circlespainter** [comment]
Hi, the situation is a bit more articulate ([ref](https://github.com/puniverse/quasar/issues/160#issuecomment-206163307)): this change causes all lambdas to be considered "suspendable", which causes Quasar's instrumentor to _analyze_ them, but not necessarily instrument them (code that don't have any suspendable call won't be instrumented by Quasar, even if it's marked as suspendable). 

The consequence of this change can be an increased JVM warming time especially in codebases with lots of lambdas, more rarely additional instrumentation (for example if you call a thread-blocking implementation through an API marked as suspendable) that anyway, if a real fiber-blocking call is not happening, will impact performance even more negligibly.

Unfortunately [lambdas can't be annotated and they can't throw checked exceptions](https://github.com/puniverse/quasar/pull/169#issue-139493334) (such as `SuspendExecution`) so this form of "automatic instrumentation" is the least evil I think.

Of course everything can be improved and if you have other ideas it's certainly worth talking about it.

**Comment by exFalso** [comment]
Ah I didn't see the `canInstrumentationBeSkipped` check in `InstrumentMethod.accept`. Thank you for the explanation!
