### ISSUE TITLE
Quasar agent causes class format error

### ISSUE THREAD

**Issue by phile314** [puniverse/quasar#184]
We are trying to use Quasar for some highly concurrent web fetching, but we have stumbled upon a problem. If we use the Quasar Java Agent, the application doesn't load due to the following error:
<pre>
Exception in thread "main" class org.apache.ignite.IgniteException: Failed to instantiate Spring XML application context [springUrl=file:/.../bot-runner/build/resources/main/example-ignite-config.xml, err=Unexpected exception parsing XML document from URL [file:/.../bot-runner/build/resources/main/example-ignite-config.xml]; nested exception is java.lang.ClassFormatError: Illegal UTF8 string in constant pool in class file org/apache/xerces/impl/xpath/regex/ParserForXMLSchema]
	at org.apache.ignite.internal.util.IgniteUtils.convertException(IgniteUtils.java:882)
	at org.apache.ignite.Ignition.start(Ignition.java:350)
	at ch.i4ds.fetchflow.flow.manager.SharedFetchflowContext.setupContext(SharedFetchflowContext.java:116)
	at ch.i4ds.fetchflow.BotRunner.sharedFetchFlowContext(BotRunner.java:72)
	at ch.i4ds.fetchflow.BotRunner.main(BotRunner.java:48)
	at ch.i4ds.fetchflow.BotRunnerExample.main(BotRunnerExample.java:23)
Caused by: class org.apache.ignite.IgniteCheckedException: Failed to instantiate Spring XML application context [springUrl=file:/.../bot-runner/build/resources/main/example-ignite-config.xml, err=Unexpected exception parsing XML document from URL [file:/.../i4ds-fetchflow/bot-runner/build/resources/main/example-ignite-config.xml]; nested exception is java.lang.ClassFormatError: Illegal UTF8 string in constant pool in class file org/apache/xerces/impl/xpath/regex/ParserForXMLSchema]
	at org.apache.ignite.internal.util.spring.IgniteSpringHelperImpl.applicationContext(IgniteSpringHelperImpl.java:391)
	at org.apache.ignite.internal.util.spring.IgniteSpringHelperImpl.loadConfigurations(IgniteSpringHelperImpl.java:104)
	at org.apache.ignite.internal.util.spring.IgniteSpringHelperImpl.loadConfigurations(IgniteSpringHelperImpl.java:98)
	at org.apache.ignite.internal.IgnitionEx.loadConfigurations(IgnitionEx.java:604)
	at org.apache.ignite.internal.IgnitionEx.start(IgnitionEx.java:805)
	at org.apache.ignite.internal.IgnitionEx.start(IgnitionEx.java:714)
	at org.apache.ignite.internal.IgnitionEx.start(IgnitionEx.java:584)
	at org.apache.ignite.internal.IgnitionEx.start(IgnitionEx.java:554)
	at org.apache.ignite.Ignition.start(Ignition.java:347)
	... 4 more
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from URL [file:/.../i4ds-fetchflow/bot-runner/build/resources/main/example-ignite-config.xml]; nested exception is java.lang.ClassFormatError: Illegal UTF8 string in constant pool in class file org/apache/xerces/impl/xpath/regex/ParserForXMLSchema
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:413)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:335)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:303)
	at org.apache.ignite.internal.util.spring.IgniteSpringHelperImpl.applicationContext(IgniteSpringHelperImpl.java:379)
	... 12 more
Caused by: java.lang.ClassFormatError: Illegal UTF8 string in constant pool in class file org/apache/xerces/impl/xpath/regex/ParserForXMLSchema
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.xerces.impl.dv.xs.XSSimpleTypeDecl.applyFacets(Unknown Source)
	at org.apache.xerces.impl.dv.xs.XSSimpleTypeDecl.applyFacets1(Unknown Source)
	at org.apache.xerces.impl.dv.xs.BaseSchemaDVFactory.createBuiltInTypes(Unknown Source)
	at org.apache.xerces.impl.dv.xs.SchemaDVFactoryImpl.createBuiltInTypes(Unknown Source)
	at org.apache.xerces.impl.dv.xs.SchemaDVFactoryImpl.<clinit>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.xerces.impl.dv.ObjectFactory.newInstance(Unknown Source)
	at org.apache.xerces.impl.dv.SchemaDVFactory.getInstance(Unknown Source)
	at org.apache.xerces.impl.dv.SchemaDVFactory.getInstance(Unknown Source)
	at org.apache.xerces.impl.xs.SchemaGrammar$BuiltinSchemaGrammar.<init>(Unknown Source)
	at org.apache.xerces.impl.xs.SchemaGrammar.<clinit>(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.<clinit>(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.configurePipeline(Unknown Source)
	at org.apache.xerces.parsers.XIncludeAwareParserConfiguration.configurePipeline(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:76)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadDocument(XmlBeanDefinitionReader.java:428)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:390)
	... 15 more
</pre>

If we remove the Quasar Java Agent, everything works fine. Class Format Error also sounds rather serious. Any idea what the problem might be? How can we debug this?

**Comment by phile314** [comment]
cc @mimba

**Comment by pron** [comment]
Basically Quasar doesn't write anything to a class's constant pool, and it doesn't seem like that particular class is instrumented at all. Maybe there's a conflict between the dependencies used by Quasar and Spring. Can you print the dependency tree for your project and look for version conflicts? Also, which Java version is that?

**Comment by phile314** [comment]
Good point, we had some unrelated version conflict problems some time ago, so this might have happened again. I will investigate.

Java version:
<pre>
openjdk version "1.8.0_76"
OpenJDK Runtime Environment (build 1.8.0_76-00)
OpenJDK 64-Bit Server VM (build 25.76-b00, mixed mode)
</pre>

**Comment by phile314** [comment]
You were right, this has nothing to do with Quasar. We are using HtmlUnit, and this seems to cause a version conflict for the xml-apis package (1.3.04 vs 1.4.01).

Thank you for your help!
