### ISSUE TITLE
Instrument failure for synchronized method even with 'm' parameter 

### ISSUE THREAD

**Issue by garretwu** [puniverse/quasar#194]
Hi,

I met instrument failure while trying to instrument class by using agent. standout has following information:

First two lines prove that 'm' parameter works for synchronized method. However, still met unable to instrument because of synchronized method error. Seems CheckInstrumentationVisitor does not check the 'm' parameter? Just curious how we step into such issues...

[quasar] WARNING: Method aaa contains synchronization
[quasar] WARNING: Method bbb contains synchronization
[quasar] ERROR: Unable to instrument class CCCC
co.paralleluniverse.fibers.instrument.UnableToInstrumentException: Unable to instrument cccccc because of synchronized method
        at co.paralleluniverse.fibers.instrument.CheckInstrumentationVisitor.visitMethod(CheckInstrumentationVisitor.java:136)
        at co.paralleluniverse.asm.ClassReader.b(Unknown Source)
        at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
        at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
        at co.paralleluniverse.fibers.instrument.MethodDatabase.checkFileAndClose(MethodDatabase.java:388)
        at co.paralleluniverse.fibers.instrument.MethodDatabase.checkClass(MethodDatabase.java:365)
        at co.paralleluniverse.fibers.instrument.MethodDatabase.getOrLoadClassEntry(MethodDatabase.java:222)
        at co.paralleluniverse.fibers.instrument.MethodDatabase.isMethodSuspendable0(MethodDatabase.java:233)
        at co.paralleluniverse.fibers.instrument.MethodDatabase.isMethodSuspendable(MethodDatabase.java:200)
        at co.paralleluniverse.fibers.instrument.InstrumentMethod.isSuspendableCall(InstrumentMethod.java:195)
        at co.paralleluniverse.fibers.instrument.InstrumentMethod.callsSuspendables(InstrumentMethod.java:161)
        at co.paralleluniverse.fibers.instrument.InstrumentClass.visitEnd(InstrumentClass.java:261)
        at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
        at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
        at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:120)
        at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:88)
        at co.paralleluniverse.fibers.instrument.JavaAgent$Transformer.transform(JavaAgent.java:187)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

BR
Gary

**Comment by circlespainter** [comment]
Hi, I tried to reproduce it in a test [here](https://github.com/circlespainter/quasar-194) but the synchronized method gets instrumented correctly (with a warning) if the agent is passed the "m" option. What's the difference w.r.t. your code/setup?

**Comment by garretwu** [comment]
Thanks @circlespainter! My project include several sub projects, sub projects has dependency and will generate their own jar ball. The issue is reported when building sub project D, while CCC is built by project C. I am not sure whether it is the root cause. My workaround is to check 'm' option in CheckInstrumentationVisitor.

**Comment by circlespainter** [comment]
So you you get the message at build time? Are you using AoT instrumentation? Is the  `allowMonitors` flag is set to `true` when running the Ant task?

**Comment by rustam9** [comment]
@circlespainter , please see my answers below:

>So do you get the message at build time?
No, at runtime. 
>Are you using AoT instrumentation? 
No, we are using the java agent, JIT I suppose.
>Is the allowMonitors flag is set to true when running the Ant task?
Yes, it's specified as -javaagent:/path/to/quasar-core-0.7.5.jar=mb

**Comment by circlespainter** [comment]
You should now find a fixed `0.7.6-SNAPSHOT` on SonaType. Thanks for troubleshooting support.
