### ISSUE TITLE
Shouldn't <tryAcquireSharedNanos> method be @Suspendable?

### ISSUE THREAD

**Issue by hongj-sh** [puniverse/quasar#217]
co.paralleluniverse.strands.concurrent.CountDownLatch.await() is okay, but await with timeout throws exception like below. I found that tryAcquireSharedNanos method of AbstractQueuedSynchronizer class was not annotated with @Suspendable. Was this intended?
===================================================================
Exception in Fiber "fiber-10000001" java.lang.AssertionError
        at co.paralleluniverse.strands.concurrent.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1358)
        at co.paralleluniverse.strands.concurrent.CountDownLatch.await(CountDownLatch.java:268)
        at com.example.Consumer.lambda$main$ba7cc617$1(Consumer.java:118)
        at co.paralleluniverse.fibers.Fiber.run(Fiber.java:1027)
WARNING: Uninstrumented methods (marked '**') or call-sites (marked '!!') detected on the call stack:
        at co.paralleluniverse.strands.concurrent.AbstractQueuedSynchronizer.tryAcquireSharedNanos(int,long) (AbstractQueuedSynchronizer.java:1358 bci: 43) **
        at co.paralleluniverse.strands.concurrent.CountDownLatch.await (CountDownLatch.java:268 bci: 10) **
        at com.example.Consumer.lambda$main$ba7cc617$1 (Consumer.java:118 bci: 1296)
        at co.paralleluniverse.fibers.Fiber.run (Fiber.java:1027 bci: 11)
        at co.paralleluniverse.fibers.Fiber.run1 (Fiber.java:1022 bci: 1)

**Comment by linkerlin** [comment]
Agreed.
