### ISSUE TITLE
ERROR: while transforming null: null

### ISSUE THREAD

**Issue by Jonatino** [puniverse/quasar#225]
I get these errors when running quasar (latest version) with my project (uses Kotlin 1.1). Not sure if this issue is directly related to #223 

`[quasar] ERROR: while transforming null: null
java.lang.IllegalArgumentException
    at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.getMethodDatabase(QuasarInstrumentor.java:147)
    at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:99)
    at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:85)
    at co.paralleluniverse.fibers.instrument.JavaAgent$Transformer.transform(JavaAgent.java:190)
    at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
    at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
    at sun.misc.Unsafe.defineAnonymousClass(Native Method)
    at java.lang.invoke.InnerClassLambdaMetafactory.spinInnerClass(InnerClassLambdaMetafactory.java:326)
    at java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:194)
    at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:304)
    at java.lang.invoke.CallSite.makeSite(CallSite.java:302)
    at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
    at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
    at sun.awt.windows.WToolkit.registerShutdownHook(WToolkit.java:279)
    at sun.awt.windows.WToolkit.run(WToolkit.java:297)
    at java.lang.Thread.run(Thread.java:745)
[quasar] ERROR: while transforming null: null
java.lang.IllegalArgumentException
    at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.getMethodDatabase(QuasarInstrumentor.java:147)
    at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:99)
    at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:85)
    at co.paralleluniverse.fibers.instrument.JavaAgent$Transformer.transform(JavaAgent.java:190)
    at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
    at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
    at sun.misc.Unsafe.defineAnonymousClass(Native Method)
    at java.lang.invoke.InvokerBytecodeGenerator.loadAndInitializeInvokerClass(InvokerBytecodeGenerator.java:284)
    at java.lang.invoke.InvokerBytecodeGenerator.loadMethod(InvokerBytecodeGenerator.java:276)
    at java.lang.invoke.InvokerBytecodeGenerator.generateCustomizedCode(InvokerBytecodeGenerator.java:618)
    at java.lang.invoke.LambdaForm.compileToBytecode(LambdaForm.java:654)
    at java.lang.invoke.Invokers.callSiteForm(Invokers.java:381)
    at java.lang.invoke.Invokers.linkToTargetMethod(Invokers.java:347)
    at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:314)
    at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
    at sun.awt.windows.WToolkit.registerShutdownHook(WToolkit.java:279)
    at sun.awt.windows.WToolkit.run(WToolkit.java:297)
    at java.lang.Thread.run(Thread.java:745)
[quasar] ERROR: while transforming null: null
java.lang.IllegalArgumentException
    at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.getMethodDatabase(QuasarInstrumentor.java:147)
    at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:99)
    at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:85)
    at co.paralleluniverse.fibers.instrument.JavaAgent$Transformer.transform(JavaAgent.java:190)
    at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
    at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
    at sun.misc.Unsafe.defineAnonymousClass(Native Method)
    at java.lang.invoke.InvokerBytecodeGenerator.loadAndInitializeInvokerClass(InvokerBytecodeGenerator.java:284)
    at java.lang.invoke.InvokerBytecodeGenerator.loadMethod(InvokerBytecodeGenerator.java:276)
    at java.lang.invoke.InvokerBytecodeGenerator.generateCustomizedCode(InvokerBytecodeGenerator.java:618)
    at java.lang.invoke.LambdaForm.compileToBytecode(LambdaForm.java:654)
    at java.lang.invoke.DirectMethodHandle.makePreparedLambdaForm(DirectMethodHandle.java:247)
    at java.lang.invoke.DirectMethodHandle.preparedLambdaForm(DirectMethodHandle.java:187)
    at java.lang.invoke.DirectMethodHandle.preparedLambdaForm(DirectMethodHandle.java:176)
    at java.lang.invoke.DirectMethodHandle.make(DirectMethodHandle.java:80)
    at java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:1655)
    at java.lang.invoke.MethodHandles$Lookup.getDirectMethodNoSecurityManager(MethodHandles.java:1612)
    at java.lang.invoke.MethodHandles$Lookup.getDirectMethodForConstant(MethodHandles.java:1797)
    at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1746)
    at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477)
    at sun.awt.windows.WToolkit.lambda$registerShutdownHook$0(WToolkit.java:280)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.awt.windows.WToolkit.registerShutdownHook(WToolkit.java:279)
    at sun.awt.windows.WToolkit.run(WToolkit.java:297)
    at java.lang.Thread.run(Thread.java:745)
[quasar] ERROR: while transforming null: null
java.lang.IllegalArgumentException
    at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.getMethodDatabase(QuasarInstrumentor.java:147)
    at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:99)
    at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:85)
    at co.paralleluniverse.fibers.instrument.JavaAgent$Transformer.transform(JavaAgent.java:190)
    at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
    at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
    at sun.misc.Unsafe.defineAnonymousClass(Native Method)
    at java.lang.invoke.InnerClassLambdaMetafactory.spinInnerClass(InnerClassLambdaMetafactory.java:326)
    at java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:194)
    at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:304)
    at java.lang.invoke.CallSite.makeSite(CallSite.java:302)
    at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
    at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
    at sun.awt.windows.WToolkit.lambda$registerShutdownHook$0(WToolkit.java:280)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.awt.windows.WToolkit.registerShutdownHook(WToolkit.java:279)
    at sun.awt.windows.WToolkit.run(WToolkit.java:297)
    at java.lang.Thread.run(Thread.java:745)`

**Comment by circlespainter** [comment]
Hi @Jonatino, it doesn't seem to be especially related to Kotlin 1.1. Which Quasar version were you using and which JDK? Are you using anything doing class loading tricks (JEE app servers or servlet containers, OSGI, ...)? If you could share a simple test project that reproduces the problem it would help because I've just tried with a simple Quasar-Kotlin project (Quasar `0.7.8-SNAPSHOT` from current `HEAD`, project compiled with Kotlin 1.1.1) and I can't reproduce it.
