### ISSUE TITLE
NPE @ 0.7.6

### ISSUE THREAD

**Issue by linkerlin** [puniverse/quasar#226]
java.lang.NullPointerException
    at co.paralleluniverse.common.reflection.ASMUtil.getClassInputStream(ASMUtil.java:37)
    at co.paralleluniverse.common.reflection.ASMUtil.getClassInputStream(ASMUtil.java:41)
    at co.paralleluniverse.common.reflection.ASMUtil.accept(ASMUtil.java:80)
    at co.paralleluniverse.common.util.ExtendedStackTrace.getMethod(ExtendedStackTrace.java:96)
    at co.paralleluniverse.common.util.ExtendedStackTrace$BasicExtendedStackTraceElement.getMethod(ExtendedStackTrace.java:188)
    at co.paralleluniverse.fibers.instrument.SuspendableHelper.lookupMethod(SuspendableHelper.java:50)
    at co.paralleluniverse.fibers.Fiber.checkInstrumentation(Fiber.java:1650)
    at co.paralleluniverse.fibers.Fiber.access$100(Fiber.java:79)
    at co.paralleluniverse.fibers.Fiber$1.uncaughtException(Fiber.java:119)
    at co.paralleluniverse.fibers.Fiber.onException(Fiber.java:1115)
    at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:788)
    at co.paralleluniverse.fibers.FiberForkJoinScheduler$FiberForkJoinTask.exec1(FiberForkJoinScheduler.java:265)
    at co.paralleluniverse.concurrent.forkjoin.ParkableForkJoinTask.doExec(ParkableForkJoinTask.java:117)
    at co.paralleluniverse.concurrent.forkjoin.ParkableForkJoinTask.exec(ParkableForkJoinTask.java:74)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Exception in Fiber "SSTcpSERVER" java.nio.channels.ConnectionPendingException
    at sun.nio.ch.UnixAsynchronousSocketChannelImpl.implConnect(UnixAsynchronousSocketChannelImpl.java:314)
    at sun.nio.ch.AsynchronousSocketChannelImpl.connect(AsynchronousSocketChannelImpl.java:209)
    at co.paralleluniverse.fibers.io.AsyncFiberSocketChannel$2.requestAsync(AsyncFiberSocketChannel.java:65)
    at co.paralleluniverse.fibers.FiberAsync$2.run(FiberAsync.java:193)
    at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:765)
    at co.paralleluniverse.fibers.FiberForkJoinScheduler$FiberForkJoinTask.exec1(FiberForkJoinScheduler.java:265)
    at co.paralleluniverse.concurrent.forkjoin.ParkableForkJoinTask.doExec(ParkableForkJoinTask.java:117)
    at co.paralleluniverse.concurrent.forkjoin.ParkableForkJoinTask.exec(ParkableForkJoinTask.java:74)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by linkerlin** [comment]
When I start connections more than 5 , It will happen.

**Comment by pron** [comment]
Seems harmless, but I've made a change to suppress the printing of the exception (it is only displaying, not propagating, correct?)
