### ISSUE TITLE
How to deal with FiberAsync.run():121 NullPointerException in exception handling?

### ISSUE THREAD

**Issue by HellScre4m** [puniverse/quasar#236]
Hi. During writing my code, I noticed that sometimes this exception is thrown:
```
java.lang.NullPointerException
	at co.paralleluniverse.fibers.FiberAsync.run(FiberAsync.java:121)
	at ...
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1067)
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:767)
	at co.paralleluniverse.fibers.FiberForkJoinScheduler$FiberForkJoinTask.exec1(FiberForkJoinScheduler.java:266)
	at co.paralleluniverse.concurrent.forkjoin.ParkableForkJoinTask.doExec(ParkableForkJoinTask.java:117)
	at co.paralleluniverse.concurrent.forkjoin.ParkableForkJoinTask.exec(ParkableForkJoinTask.java:74)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
However it seems that executor catches this exception ( I don't know if it causes performance problems or not, but it is running normally). I also got that this exception is thrown everywhere you are dealing with FiberAsync, for example when working with comsat-httpclient or dealing directly with FiberAsync (wrapping MongoDB Async Driver).
So please
1. Tell me if this causes performance stalls or not
2. MongoDB Async Driver` throws Throwable`, so in exception handling I have two options. First is to catch this `NullPointerException`, which I don't know if it is OK for Quasar executor (tell me) or to throw it again (which makes troubles for me because I have a highly nested method call and this is exhausting to deal with `throws NullPointerException` in all method signatures).

Thanks for helping

**Comment by pron** [comment]
This is not good and should not be happening if the code is properly instrumented. Can you provide more details?

**Comment by HellScre4m** [comment]
You are right the problem is solved. I had a few functions that were not instrumented.
However  a new issue arised. Right now after upgrading to 0.77 when I want to run in debugging mode I face this error:
```
[quasar] ERROR: while transforming co/paralleluniverse/strands/Strand: null
java.lang.NullPointerException
	at co.paralleluniverse.fibers.instrument.Classes.isYieldMethod(Classes.java:61)
	at co.paralleluniverse.fibers.instrument.LabelSuspendableCallSitesClassVisitor.visitMethod(LabelSuspendableCallSitesClassVisitor.java:47)
	at co.paralleluniverse.asm.ClassReader.b(Unknown Source)
	at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
	at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
	at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:121)
	at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:88)
	at co.paralleluniverse.fibers.instrument.JavaAgent$Transformer.transform(JavaAgent.java:190)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at co.paralleluniverse.fibers.instrument.Classes.<clinit>(Classes.java:39)
	at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.shouldInstrument(QuasarInstrumentor.java:72)
	at co.paralleluniverse.fibers.instrument.JavaAgent$Transformer.transform(JavaAgent.java:179)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.findBootstrapClass(Native Method)
	at java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1012)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:413)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[quasar] ERROR: while transforming co/paralleluniverse/fibers/Stack: null
java.lang.NullPointerException
	at co.paralleluniverse.fibers.instrument.Classes.isYieldMethod(Classes.java:61)
	at co.paralleluniverse.fibers.instrument.MethodDatabase.isMethodSuspendable0(MethodDatabase.java:191)
	at co.paralleluniverse.fibers.instrument.MethodDatabase.isMethodSuspendable(MethodDatabase.java:161)
	at co.paralleluniverse.fibers.instrument.InstrumentMethod.isSuspendableCall(InstrumentMethod.java:224)
	at co.paralleluniverse.fibers.instrument.LabelSuspendableCallSitesClassVisitor$1.visitMethodInsn(LabelSuspendableCallSitesClassVisitor.java:64)
	at co.paralleluniverse.asm.ClassReader.a(Unknown Source)
	at co.paralleluniverse.asm.ClassReader.b(Unknown Source)
	at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
	at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
	at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:121)
	at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:88)
	at co.paralleluniverse.fibers.instrument.JavaAgent$Transformer.transform(JavaAgent.java:190)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at co.paralleluniverse.fibers.instrument.Classes.<clinit>(Classes.java:41)
	at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.shouldInstrument(QuasarInstrumentor.java:72)
	at co.paralleluniverse.fibers.instrument.JavaAgent$Transformer.transform(JavaAgent.java:179)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.findBootstrapClass(Native Method)
	at java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1012)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:413)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```
I receive this exception multiple times (only) in debugging mode when it starts to run. I can't get why, but still program works normally without problems (after running ends). I know I should open a new issue. Sorry but I think maybe solution to this one is trivial like previous one. Right now I'm completely sure that I instrumented every function properly. And one extra thing, I'm using static class initializes now. Using IDEA

**Comment by roberterdin** [comment]
I face the same issue, so I'm not sure it's related to your previous one.

**Comment by pron** [comment]
@HellScre4m This is weird. The NPE seems to be a result of a static final fields not having been initialized. Could this be some problem with the debugger?

**Comment by pron** [comment]
@roberterdin Which one? The first? It was due to uninstrumented methods.

**Comment by roberterdin** [comment]
@pron No, the second with the `NullPointerException` when attaching the debugger. I can confirm that it does work anyway.

**Comment by HellScre4m** [comment]
@pron I use final static fields with `static{}` initializers, but I'm certainly sure that I initialize all the fields. Also when I run my code in run mode I face no exceptions, but when I use debugger, there are lots of this type of exception. I also confirm @roberterdin that it does work anyway.
As debugger I use Intellij IDEA internal debugger which binds to a JVM socket.

**Comment by pron** [comment]
Can you try now with the SNAPSHOT version (on Sonatype)?

**Comment by HellScre4m** [comment]
The problem is solved using `co.paralleluniverse:quasar-core:0.7.8-20170117.084120-3`
I see no more exceptions of this kind. Thanks for solving this issue.
