### ISSUE TITLE
quasar-core agent fails to run on JDK9+160

### ISSUE THREAD

**Issue by chrisr3** [puniverse/quasar#253]
I have a project that is compiled for JDK8, but that I am trying to run on JDK9. However, the `quasar-core` agent is failing to instrument:
```
[quasar] ERROR: while transforming jdk/internal/vm/PostVMInitHook: null
java.lang.IllegalArgumentException
        at co.paralleluniverse.asm.ClassReader.<init>(Unknown Source)
        at co.paralleluniverse.asm.ClassReader.<init>(Unknown Source)
        at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:118)
        at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:88)
        at co.paralleluniverse.fibers.instrument.JavaAgent$Transformer.transform(JavaAgent.java:190)
        at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:190)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
[quasar] ERROR: java/lang/Object
java.lang.IllegalArgumentException
        at co.paralleluniverse.asm.ClassReader.<init>(Unknown Source)
        at co.paralleluniverse.asm.ClassReader.<init>(Unknown Source)
        at co.paralleluniverse.asm.ClassReader.<init>(Unknown Source)
        at co.paralleluniverse.fibers.instrument.MethodDatabase.checkFileAndClose(MethodDatabase.java:344)
        ...
```

I am suspecting that this is because the latest JDK9 snapshots have removed some internal APIs that Quasar is using, e.g. according to `jdeps -jdkinternals quasar-core-0.7.8-SNAPSHOT-jdk8.jar`:

```
JDK Internal API                         Suggested Replacement
----------------                         ---------------------
sun.misc.Resource                        Removed. See http://openjdk.java.net/jeps/260
sun.misc.URLClassPath                    Removed. See http://openjdk.java.net/jeps/260
sun.misc.Unsafe                          See http://openjdk.java.net/jeps/260
```

**Comment by circlespainter** [comment]
AFAIK JDK9 is not really supported at this stage. @pron Is that correct and do you know of any news about that?

**Comment by atulg-fw** [comment]
Is this issue solved? 
I am facing a similar issue while running on open jdk 11

**Comment by jhchee** [comment]
Does this not work with java 9, I head over here after seeing this.
<img width="698" alt="image" src="https://user-images.githubusercontent.com/33974196/159429035-d8f2850d-98f6-4e19-a5c7-bbeb68e79f75.png">

**Comment by TinyZzh** [comment]
> Does this not work with java 9, I head over here after seeing this. <img alt="image" width="698" src="https://user-images.githubusercontent.com/33974196/159429035-d8f2850d-98f6-4e19-a5c7-bbeb68e79f75.png">

upgrade asm version to 9.x
