### ISSUE TITLE
Regression: 0.7.8 verification failing on method declared in suspendable-supers

### ISSUE THREAD

**Issue by victornoel** [puniverse/quasar#279]
Hi,

It worked well before, but since 0.7.8, with the following code:
```
    private <R, T extends CockpitRequest<R>> void answer(T r, CheckedFunction1<T, R> f) throws SuspendExecution {
        try {
            RequestReplyHelper.reply(r, f.apply(r));
        } catch (Throwable e) {
            RequestReplyHelper.replyError(r, e);
        }
    }
```

And the following in my `META-INF/suspendable-supers`:
```
javaslang.CheckedFunction1.apply
```

I get this instrumentation error:
```
! at org.ow2.petals.cockpit.server.actors.WorkspaceActor.answer(org.ow2.petals.cockpit.server.actors.CockpitActors$CockpitRequest,javaslang.CheckedFunction1) (WorkspaceActor.java:209) !! (instrumented suspendable calls at: lines [209, 209, 211],  calls [co.paralleluniverse.actors.behaviors.RequestReplyHelper.reply(co.paralleluniverse.actors.behaviors.RequestMessage, java.lang.Object), co.paralleluniverse.actors.behaviors.RequestReplyHelper.replyError(co.paralleluniverse.actors.behaviors.RequestMessage, java.lang.Throwable), javaslang.CheckedFunction1.apply(java.lang.Object)])
```

I'm not sure if it is the same as #275...

**Comment by circlespainter** [comment]
Hi, I might be not reproducing your case accurately but this one works OK for me in `0.7.8` with `testgrp.ChkFun1.apply` as the only line in `META-INF/suspendable-supers` (and the verification complains correctly if the line is not there):

```java
import co.paralleluniverse.actors.ActorRef;
import co.paralleluniverse.actors.BasicActor;
import co.paralleluniverse.actors.LocalActor;
import co.paralleluniverse.actors.behaviors.RequestMessage;
import co.paralleluniverse.actors.behaviors.RequestReplyHelper;
import co.paralleluniverse.fibers.Fiber;
import co.paralleluniverse.fibers.SuspendExecution;
import co.paralleluniverse.fibers.Suspendable;

import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

interface ChkFun1<T, R> {
    R apply(T t);
}

class ChkFunSl<T, R> implements ChkFun1<T, R> {
    @Override
    @Suspendable
    public R apply(T t) {
        try {
            Fiber.sleep(1000);
        } catch (final InterruptedException e) {
            throw new RuntimeException(e);
        } catch (final SuspendExecution se) {
            throw new AssertionError(se);
        }
        return null;
    }
}

class RM extends RequestMessage<Object> {
    private final Object content;

    RM(Object content) {
        this.content = content;
    }

    public final Object getContent() {
        return content;
    }
}

class MyActor extends BasicActor<RM, Void> {
    @Override
    protected Void doRun() throws InterruptedException, SuspendExecution {
        final RM m = receive();
        final ChkFun1 h = new ChkFunSl<Void, Void>();
        System.out.println(h.apply(m));
        RequestReplyHelper.reply(m, new Object());
        return null;
    }
}

public final class Main {
    public static void main(String[] args) throws InterruptedException, ExecutionException, TimeoutException, SuspendExecution {
        final ActorRef<? super RM> ref = new MyActor().spawn();
        final Object ret = RequestReplyHelper.call(ref, new RM(new Object()));
        System.out.println(ret);
        LocalActor.join(ref, 10, TimeUnit.SECONDS);
    }
}
```

Can you provide a snippet or sample project that reproduces it, or give indications as to how to modify the above?

**Comment by victornoel** [comment]
I just ran your example (from Eclipse if it is important...) with the following JVM options:
`-javaagent:/home/victor/.m2/repository/co/paralleluniverse/quasar-core/0.7.8/quasar-core-0.7.8.jar -Dco.paralleluniverse.fibers.verifyInstrumentation=true`

and Maven pom.xml:
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>test</groupId>
    <artifactId>test</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>co.paralleluniverse</groupId>
            <artifactId>quasar-core</artifactId>
            <version>0.7.8</version>
        </dependency>
        <dependency>
            <groupId>co.paralleluniverse</groupId>
            <artifactId>quasar-actors</artifactId>
            <version>0.7.8</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.21</version>
        </dependency>
    </dependencies>
</project>
```

And I get the following stacktrace:
```
WARNING: Uninstrumented whole methods ('**') or single calls ('!!') detected: 
	at co.paralleluniverse.common.util.ExtendedStackTrace.here() (ExtendedStackTrace.java:46)
	at co.paralleluniverse.fibers.Fiber.checkInstrumentation() (Fiber.java:1694)
	at co.paralleluniverse.fibers.Fiber.verifySuspend(co.paralleluniverse.fibers.Fiber) (Fiber.java:1667)
	at co.paralleluniverse.fibers.Fiber.verifySuspend() (Fiber.java:1662)
	at co.paralleluniverse.fibers.Fiber.sleep(long,java.util.concurrent.TimeUnit) (Fiber.java:693)
	at co.paralleluniverse.fibers.Fiber.sleep(long) (Fiber.java:685)
	at test.ChkFunSl.apply(java.lang.Object) (Main.java:24)
	at test.MyActor.doRun() (Main.java:51) !! (instrumented suspendable calls at: lines [49, 52],  calls [test.MyActor.receive(), co.paralleluniverse.actors.behaviors.RequestReplyHelper.reply(co.paralleluniverse.actors.behaviors.RequestMessage, java.lang.Object)])
	at test.MyActor.doRun() (Main.java:1) (optimized)
	at co.paralleluniverse.actors.Actor.run0() (Actor.java:710)
	at co.paralleluniverse.actors.ActorRunner.run() (ActorRunner.java:51)
	at co.paralleluniverse.fibers.Fiber.run() (Fiber.java:1097)
	at co.paralleluniverse.fibers.Fiber.run1() (Fiber.java:1092)
Exception in Fiber "fiber-10000001" If this exception looks strange, perhaps you've forgotten to instrument a blocking method. Run your program with -Dco.paralleluniverse.fibers.verifyInstrumentation to catch the culprit!
java.lang.NullPointerException
	at co.paralleluniverse.strands.Strand.park(Strand.java:536)
	at co.paralleluniverse.strands.ConditionSynchronizer.await(ConditionSynchronizer.java:54)
	at co.paralleluniverse.strands.channels.SingleConsumerQueueChannel.receive(SingleConsumerQueueChannel.java:94)
	at co.paralleluniverse.actors.Actor.receive(Actor.java:481)
	at test.MyActor.doRun(Main.java:49)
	at test.MyActor.doRun(Main.java:1)
	at co.paralleluniverse.actors.Actor.run0(Actor.java:710)
	at co.paralleluniverse.actors.ActorRunner.run(ActorRunner.java:51)
	at co.paralleluniverse.fibers.Fiber.run(Fiber.java:1097)
Exception in thread "main" java.lang.NullPointerException
	at co.paralleluniverse.strands.Strand.park(Strand.java:536)
	at co.paralleluniverse.strands.ConditionSynchronizer.await(ConditionSynchronizer.java:54)
	at co.paralleluniverse.strands.channels.SingleConsumerQueueChannel.receive(SingleConsumerQueueChannel.java:94)
	at co.paralleluniverse.actors.Actor.receive(Actor.java:481)
	at test.MyActor.doRun(Main.java:49)
	at test.MyActor.doRun(Main.java:1)
	at co.paralleluniverse.actors.Actor.run0(Actor.java:710)
	at co.paralleluniverse.actors.ActorRunner.run(ActorRunner.java:51)
	at co.paralleluniverse.fibers.Fiber.run(Fiber.java:1097)
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1092)
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:788)
	at co.paralleluniverse.fibers.FiberForkJoinScheduler$FiberForkJoinTask.exec1(FiberForkJoinScheduler.java:266)
	at co.paralleluniverse.concurrent.forkjoin.ParkableForkJoinTask.doExec(ParkableForkJoinTask.java:117)
	at co.paralleluniverse.concurrent.forkjoin.ParkableForkJoinTask.exec(ParkableForkJoinTask.java:74)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:261)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:988)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

So it's not even working, I guess there is something very strange there... (or I made a stupid mistake trying to run your example from scratch ^^).

**Comment by victornoel** [comment]
deleted my previous comment, sorry, I completely forgot the META-INF file :P sorry, I will get back when I can reproduce my initial problem ^^

**Comment by victornoel** [comment]
Here is a reproductive example:
```
package test;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

import co.paralleluniverse.actors.ActorRef;
import co.paralleluniverse.actors.BasicActor;
import co.paralleluniverse.actors.LocalActor;
import co.paralleluniverse.actors.behaviors.RequestMessage;
import co.paralleluniverse.actors.behaviors.RequestReplyHelper;
import co.paralleluniverse.fibers.Fiber;
import co.paralleluniverse.fibers.SuspendExecution;
import co.paralleluniverse.fibers.Suspendable;

interface ChkFun1<T, R> {
    R apply(T t);
}

class RM extends RequestMessage<Object> {
    private final Object content;

    RM(Object content) {
        this.content = content;
    }

    public final Object getContent() {
        return content;
    }
}

class MyActor extends BasicActor<RM, Void> {
    @Override
    protected Void doRun() throws InterruptedException, SuspendExecution {
        final RM m = receive();
        answer(m, this::doSomething);
        return null;
    }
    
    @Suspendable
    public Object doSomething(Object o) {
        System.out.println(o);
        try {
            Fiber.sleep(1000);
        } catch (final InterruptedException e) {
            throw new RuntimeException(e);
        } catch (final SuspendExecution se) {
            throw new AssertionError(se);
        }
        return null;
    }
    
    private <R, T extends RequestMessage<R>> void answer(T r, ChkFun1<T, R> f) throws SuspendExecution {
        try {
            RequestReplyHelper.reply(r, f.apply(r));
        } catch (Throwable e) {
            RequestReplyHelper.replyError(r, e);
        }
    }

}

public final class Main {
    public static void main(String[] args) throws InterruptedException, ExecutionException, TimeoutException, SuspendExecution {
        final ActorRef<? super RM> ref = new MyActor().spawn();
        final Object ret = RequestReplyHelper.call(ref, new RM(new Object()));
        System.out.println(ret);
        LocalActor.join(ref, 10, TimeUnit.SECONDS);
    }
}
```

I had to use a lambda I think to exhibit the problem!

**Comment by circlespainter** [comment]
Yes, it is indeed a regression from 0.7.7 to 0.7.8 introduced by name-based call-site instrumentation verification (https://github.com/puniverse/quasar/commit/24e9e5d8a331e4e924d5985fe5d2fcbae0faaf77#diff-4ef312b5913c12763d2e00ecfd5962f2) which, in its current form and in this case, doesn't work because the actual method call in the stack is provided through a method reference and has a different name from the interface method (and also a different owner with a completely separate hierarchy).

I'll need to think a bit about how this case can be covered.

**Comment by circlespainter** [comment]
It looks to me like, starting with lambdas, many more stack traces are possible than previously and specifically there are new traces where the caller is a functional interface call site and the callee can be pretty much anything with a compatible signature, including methods with a different name and in a completely unrelated hierarchy.

We should probably be less demanding when checking that a functional interface call site is instrumented, that is allow anything with a desc compatible with one of the functional ones we found during instrumentation. Of course the chance for false OKs would become bigger as we'd be less selective in this case, but maybe not by a lot if we manage to behave like this only for functional interfaces.

@pron What do you think?
