### ISSUE TITLE
Quasar 0.7.8: java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file

### ISSUE THREAD

**Issue by Jonatino** [puniverse/quasar#284]
java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file nl/bartpelle/veteres/services/worldlist/WorldListServer
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_131]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_131]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_131]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_131]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_131]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_131]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_131]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_131]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_131]
	at nl.bartpelle.veteres.GameServer.setupSlowServices(GameServer.java:269) ~[classes/:?]
	at nl.bartpelle.veteres.GameServer.start(GameServer.java:183) ~[classes/:?]
	at nl.bartpelle.veteres.GameServer.main(GameServer.java:460) ~[classes/:?]

**Comment by Jonatino** [comment]
Was due to me using Thread.sleep instead of Strand.sleep. Should this really cause a program to fail to start though?

**Comment by pron** [comment]
This is a bug that occurs in some cases where instrumentation fails. It has been fixed, and you can try it in `0.7.9-SNAPSHOT`. However, you will likely and instrumentation error, instead, for using a blocking method.
