### ISSUE TITLE
Instrumentation fails for classes loaded through the bootstrap ClassLoader

### ISSUE THREAD

**Issue by exFalso** [puniverse/quasar#302]
```
[quasar] ERROR: while transforming com/intellij/rt/debugger/agent/CaptureStorage$InsertMatch: null
java.lang.IllegalArgumentException
    at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.getMethodDatabase(QuasarInstrumentor.java:181)
    at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:108)
    at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:94)
    at co.paralleluniverse.fibers.instrument.JavaAgent$Transformer.transform(JavaAgent.java:209)
    at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
    at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
    at com.intellij.rt.debugger.agent.CaptureStorage.insertEnter(CaptureStorage.java:76)
    at java.util.concurrent.FutureTask.run(FutureTask.java)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```
Relevant section of JDK docs on ClassFileTransformer.transform:
```
(...)
Parameters:
loader - the defining loader of the class to be transformed, may be null if the bootstrap loader
```

**Comment by doctorpangloss** [comment]
I've encountered this issue multiple times.
