### ISSUE TITLE
Warning: scheduler: FiberForkJoinScheduler is blocking a thread

### ISSUE THREAD

**Issue by d3bt3ch** [puniverse/quasar#332]
I am getting the following warning

`WARNING: fiber Fiber@10000001[task: ParkableForkJoinTask@43d3ea9(Fiber@10000001), target: com.pixo.data.FilesRepository$$Lambda$527/0x00000008006f9040@200e4b5e, scheduler: co.paralleluniverse.fibers.FiberForkJoinScheduler@791a7fe] is blocking a thread (Thread[ForkJoinPool-pixo-data-fiber-schedular-worker-3,5,main]).
	at java.base@11.0.4/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.4/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base@11.0.4/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1079)
	at java.base@11.0.4/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1369)
	at java.base@11.0.4/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:278)
	at net.rubyeye.xmemcached.XMemcachedClient.latchWait(XMemcachedClient.java:2361)
	at net.rubyeye.xmemcached.XMemcachedClient.sendStoreCommand(XMemcachedClient.java:2345)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1252)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1306)
	at net.rubyeye.xmemcached.XMemcachedClient.set(XMemcachedClient.java:1295)`

**Comment by ioandy** [comment]
I met the same problem. Have you solved it？
