### ISSUE TITLE
WARNING: co.paralleluniverse.fibers.FiberForkJoinScheduler@4446cced] is blocking a thread

### ISSUE THREAD

**Issue by ioandy** [puniverse/quasar#336]
version 0.7.9.
```
WARNING: fiber Fiber@10000001:4e000724[task: ParkableForkJoinTask@6abd23d3(Fiber@10000001), target: co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable@7922da8e, scheduler: co.paralleluniverse.fibers.FiberForkJoinScheduler@4446cced] is blocking a thread (Thread[ForkJoinPool-default-fiber-pool-worker-1,5,main]).
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at com.ce.iot.esl.commucation.task.impl.TaskExecutor$1.run(TaskExecutor.java:94)
        at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:44)
        at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:32)
        at co.paralleluniverse.fibers.Fiber.run(Fiber.java:1097)
```
How to solve this problem？

**Comment by liruirui6174** [comment]
you solve?   i also like this

**Comment by puppyhe** [comment]
me too
