### ISSUE TITLE
JDK 14 Support

### ISSUE THREAD

**Issue by asasisekar** [puniverse/quasar#337]
We are migrating application to openjdk 14 and Quasar (0.8.0) used. Getting below error. 

```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 58
	at co.paralleluniverse.asm.ClassReader.<init>(ClassReader.java:184)
	at co.paralleluniverse.asm.ClassReader.<init>(ClassReader.java:166)
	at co.paralleluniverse.asm.ClassReader.<init>(ClassReader.java:152)
	at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:123)
	at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:102)
	at co.paralleluniverse.fibers.instrument.InstrumentationTask.instrumentClass(InstrumentationTask.java:191)
	at co.paralleluniverse.fibers.instrument.InstrumentationTask.execute(InstrumentationTask.java:178)
	... 192 more
```

**Comment by doctorpangloss** [comment]
I fixed this by updating asm to version 9.0.

**Comment by asasisekar** [comment]
@doctorpangloss Thanks for your suggestion. Did you face any challenges or issues for updating asm version to 9.0.
