### ISSUE TITLE
Instrumenting with Ant

### ISSUE THREAD

**Issue by MartinGittins** [puniverse/quasar#52]
I'm having a problem getting the Ant instrumentation to work, and need this for integration in build server.
I get this error:
[InstrumentationTask] ERROR: Unable to instrument class com/bnpp/fitt/scada/actors/ModelNode

BUILD FAILED
D:\Work2\trunk\Scada\model\build.xml:8: java.lang.NullPointerException
        at org.objectweb.asm.Item.a(Unknown Source)
        at org.objectweb.asm.ClassWriter.c(Unknown Source)
        at org.objectweb.asm.ClassWriter.a(Unknown Source)
        at org.objectweb.asm.Frame.a(Unknown Source)
        at org.objectweb.asm.Frame.a(Unknown Source)
        at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
        at co.paralleluniverse.fibers.instrument.InstrumentMethod.accept(InstrumentMethod.java:415)
        at co.paralleluniverse.fibers.instrument.InstrumentClass.visitEnd(InstrumentClass.java:241)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:100)
        at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:86)
        at co.paralleluniverse.fibers.instrument.InstrumentationTask.instrumentClass(InstrumentationTask.java:180)
        at co.paralleluniverse.fibers.instrument.InstrumentationTask.execute(InstrumentationTask.java:167)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.Main.runBuild(Main.java:851)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

This class instruments OK with the command line javaagent call.

My ant script looks like this:

<project name="Model" default="dist" basedir=".">
    <taskdef name="InstrumentationTask"
             classname="co.paralleluniverse.fibers.instrument.InstrumentationTask"
             classpath="D:\maven-repo\co\paralleluniverse\quasar-core\0.5.0\quasar-core-0.5.0.jar;D:\maven-repo\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar"/>
    <target name="instrument">
        <InstrumentationTask verbose="false">
            <fileSet dir="target\classes">
                <include name="com\bnpp\fitt\scada\actors\**/*.class"/>
            </fileSet>
        </InstrumentationTask>
    </target>
</project>

Is there something else that I need in the ant script?  asm-all-5.0 gives same error.
ModelNode is an Actor and is the first Actor class it finds - so I suspect it's something systematic.

**Comment by circlespainter** [comment]
ASM is now shared into Quasar; does this happen with recent releases still?

**Comment by pron** [comment]
Closing because the issue has most likely been resolved. Please reopen if the problem persists.
