### ISSUE TITLE
Some instrumented reflect invocations reset arguments upon call

### ISSUE THREAD

**Issue by circlespainter** [puniverse/quasar#73]
This gist https://gist.github.com/circlespainter/1b2a94eedca15b0bf221 triggers the following exception:

```
Caused by: java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at testgrp.QuasarBreakage.doIt(QuasarBreakage.java:35)
	at testgrp.QuasarBreakage$1.run(QuasarBreakage.java:44)
```

Debugging highlights that after stack management calls inserted by instrumentation, the reflect invocation arguments become `null`.

The same pattern is being used in Clojure's `Reflector` and this causes https://github.com/puniverse/pulsar/issues/29 as well.

**Comment by circlespainter** [comment]
It seems to be related to bytecode analysis for frames; this test https://github.com/puniverse/quasar/blob/fix-73/quasar-core/src/test/java/co/paralleluniverse/fibers/instrument/RTInitLocalArrayArgTest.java works ok if an object is passed instead of an array, while in the latter case analysis will return UNINITIALIZED as a bytecode type for the local, breaking the instrumented call. Leaving it for @pron.
