### ISSUE TITLE
Repeatedly calling FiberSocketChannel.open() results in java.lang.OutOfMemoryError: unable to create new native thread

### ISSUE THREAD

**Issue by mnowrot** [puniverse/quasar#74]
Having the following inside a fiber's run method

```
for(int i = 0; i < runsCount; i++) {
    // connect
    FiberSocketChannel channel = FiberSocketChannel.open();
    (...)
    channel.close();
}
```
results in "OOMError unable to create new native thread" thrown from open() when the runsCount is big enough.
After investigation, this seems to be caused by repeatedly calling FiberAsyncIO.defaultGroup();

There is a workaround:
Initialize the AsynchronousChannelGroup once per Fiber class:
```
private static final AsynchronousChannelGroup group;
static {
   try {
      group = AsynchronousChannelGroup.withThreadPool(Executors.newFixedThreadPool(4));
   } catch (IOException e) {
      throw new RuntimeException("Failed thread creation", e)
   }
}
```
and in the code above replace
```
FiberSocketChannel.open();
```
with
```
FiberSocketChannel.open(group);
```

**Comment by pron** [comment]
Can you send the full stack trace?

**Comment by mnowrot** [comment]
Yes, please see below:
```
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at sun.nio.ch.AsynchronousChannelGroupImpl$2.run(AsynchronousChannelGroupImpl.java:123)
	at sun.nio.ch.AsynchronousChannelGroupImpl$2.run(AsynchronousChannelGroupImpl.java:118)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.nio.ch.AsynchronousChannelGroupImpl.startInternalThread(AsynchronousChannelGroupImpl.java:118)
	at sun.nio.ch.AsynchronousChannelGroupImpl.startThreads(AsynchronousChannelGroupImpl.java:132)
	at sun.nio.ch.KQueuePort.start(KQueuePort.java:111)
	at sun.nio.ch.BsdAsynchronousChannelProvider.openAsynchronousChannelGroup(BsdAsynchronousChannelProvider.java:64)
	at java.nio.channels.AsynchronousChannelGroup.withThreadPool(AsynchronousChannelGroup.java:273)
	at co.paralleluniverse.fibers.io.FiberAsyncIO.defaultGroup(FiberAsyncIO.java:60)
	at co.paralleluniverse.fibers.io.FiberSocketChannel.open(FiberSocketChannel.java:55)
	at foo.bar.MyFiber.run(MyFiber.java:71)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:42)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:30)
	at co.paralleluniverse.fibers.Fiber.run(Fiber.java:1001)
```

**Comment by pron** [comment]
Can you give it a try now? The problem with the workaround is that it might harm IO performance.

**Comment by mnowrot** [comment]
Hi pron, first of all thanks for your prompt reply. I've given it a try, and the main problem was solved, however another one replaced it, please see below:
```
java.lang.NullPointerException
	at co.paralleluniverse.strands.Strand.park(Strand.java:495) ~[quasar-core-0.6.3-SNAPSHOT.jar:0.6.3-SNAPSHOT]
	at co.paralleluniverse.strands.concurrent.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:838) ~[quasar-core-0.6.3-SNAPSHOT.jar:0.6.3-SNAPSHOT]
	at co.paralleluniverse.strands.concurrent.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:872) ~[quasar-core-0.6.3-SNAPSHOT.jar:0.6.3-SNAPSHOT]
	at co.paralleluniverse.strands.concurrent.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1203) ~[quasar-core-0.6.3-SNAPSHOT.jar:0.6.3-SNAPSHOT]
	at co.paralleluniverse.strands.concurrent.ReentrantLock$NonfairSync.lock(ReentrantLock.java:207) ~[quasar-core-0.6.3-SNAPSHOT.jar:0.6.3-SNAPSHOT]
	at co.paralleluniverse.strands.concurrent.ReentrantLock.lock(ReentrantLock.java:285) ~[quasar-core-0.6.3-SNAPSHOT.jar:0.6.3-SNAPSHOT]
	at co.paralleluniverse.fibers.SchedulerLocal.get(SchedulerLocal.java:48) ~[quasar-core-0.6.3-SNAPSHOT.jar:0.6.3-SNAPSHOT]
	at co.paralleluniverse.fibers.io.FiberAsyncIO.defaultGroup(FiberAsyncIO.java:62) ~[quasar-core-0.6.3-SNAPSHOT.jar:0.6.3-SNAPSHOT]
	at co.paralleluniverse.fibers.io.FiberSocketChannel.open(FiberSocketChannel.java:55) ~[quasar-core-0.6.3-SNAPSHOT.jar:0.6.3-SNAPSHOT]
	at foo.bar.MyFiber.run(MyFiber.java:61) [main/:?]
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:42) [quasar-core-0.6.3-SNAPSHOT.jar:0.6.3-SNAPSHOT]
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:30) [quasar-core-0.6.3-SNAPSHOT.jar:0.6.3-SNAPSHOT]
	at co.paralleluniverse.fibers.Fiber.run(Fiber.java:1012) [quasar-core-0.6.3-SNAPSHOT.jar:0.6.3-SNAPSHOT]
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1007) [quasar-core-0.6.3-SNAPSHOT.jar:0.6.3-SNAPSHOT]
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:719) [quasar-core-0.6.3-SNAPSHOT.jar:0.6.3-SNAPSHOT]
	at co.paralleluniverse.fibers.FiberForkJoinScheduler$FiberForkJoinTask.exec1(FiberForkJoinScheduler.java:248) [quasar-core-0.6.3-SNAPSHOT.jar:0.6.3-SNAPSHOT]
	at co.paralleluniverse.concurrent.forkjoin.ParkableForkJoinTask.doExec(ParkableForkJoinTask.java:116) [quasar-core-0.6.3-SNAPSHOT.jar:0.6.3-SNAPSHOT]
	at co.paralleluniverse.concurrent.forkjoin.ParkableForkJoinTask.exec(ParkableForkJoinTask.java:73) [quasar-core-0.6.3-SNAPSHOT.jar:0.6.3-SNAPSHOT]
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:261) [quasar-core-0.6.3-SNAPSHOT.jar:0.6.3-SNAPSHOT]
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:988) [quasar-core-0.6.3-SNAPSHOT.jar:0.6.3-SNAPSHOT]
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1628) [quasar-core-0.6.3-SNAPSHOT.jar:0.6.3-SNAPSHOT]
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [quasar-core-0.6.3-SNAPSHOT.jar:0.6.3-SNAPSHOT]
```

**Comment by pron** [comment]
Sorry about that. Can you try it now?

**Comment by mnowrot** [comment]
No problem at all - works like a charm now. Thanks :)
