### ISSUE TITLE
gratuitous reporting of exceptions in fibers

### ISSUE THREAD

**Issue by dehubbed** [puniverse/quasar#77]
An exception thrown in a fiber, e.g. (from pulsar):
````
(spawn-fiber #(/ 1 0))
````
gets reported on the console, with a stack trace:
````
Exception in Fiber "fiber-10000001" java.lang.ArithmeticException: Divide by zero
	at clojure.lang.Numbers.divide(Numbers.java:156)
	at clojure.lang.Numbers.divide(Numbers.java:3731)
	at clj_ccnr.reactive$eval2193$fn__2194.invoke(NO_SOURCE_FILE:1)
	at co.paralleluniverse.pulsar.InstrumentedIFn.invoke(InstrumentedIFn.java:32)
	at co.paralleluniverse.pulsar.ClojureHelper.suspendableInvoke(ClojureHelper.java:185)
	at co.paralleluniverse.pulsar.ClojureHelper$3.run(ClojureHelper.java:172)
	at co.paralleluniverse.fibers.Fiber.run(Fiber.java:1003
````
In particular I start and cancel a lot of futures/fibers:
````
(def f (spawn-fiber #(deref (promise))))
(future-cancel f)
````
Each time I get:
````
Exception in Fiber "fiber-10000001" java.lang.RuntimeException: java.lang.InterruptedException
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:763)
	at co.paralleluniverse.fibers.FiberForkJoinScheduler$FiberForkJoinTask.exec1(FiberForkJoinScheduler.java:248)
	at co.paralleluniverse.concurrent.forkjoin.ParkableForkJoinTask.doExec(ParkableForkJoinTask.java:116)
	at co.paralleluniverse.concurrent.forkjoin.ParkableForkJoinTask.exec(ParkableForkJoinTask.java:73)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:261)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:988)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
````
Can this be switched off? Somehow I can't even find the code in Quasar that does the printStackTrace.

**Comment by pron** [comment]
`Fiber.setDefaultUncaughtExceptionHandler(yourDefaultExceptionHandler)`

**Comment by dehubbed** [comment]
Thanks. I guess this is an artifact of fibers being both drop-ins for threads and futures. While threads typically handle their own exceptions, it is customary for futures to NOT handle their own exceptions but escalate them to the submitter, that's what ExecutionException is for. Maybe this can be accommodated somehow.

**Comment by pron** [comment]
Exceptions are propagated as `ExecutionException` when you `get()` or `join()`. If you set an uncaught-exception handler that does nothing, you'll have the same behavior as any other future.

**Comment by dehubbed** [comment]
Yes I have this do-nothing handler now I just wished it could distinguish between fiber-as-a-thread and fiber-as-a-future. (I.e. only do nothing in the future case).

**Comment by pron** [comment]
You can set an uncaught exception handler on each fiber separately (`setUncaughtExceptionHandler` instead of `setDefaultUncaughtExceptionHandler`).

**Comment by dehubbed** [comment]
Ah. Very good. I'll do that. Thank you very much.
