### ISSUE TITLE
invalid IllegalStateException on cancelled Fiber

### ISSUE THREAD

**Issue by dehubbed** [puniverse/quasar#78]
When spawning a fiber and immediately cancelling it afterwards:
```
(let [f (spawn-fiber #(println "foo"))]
  (future-cancel f))
```
I get
```
Exception in Fiber "fiber-10000001" java.lang.IllegalStateException: Not new or suspended
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:688)
	at co.paralleluniverse.fibers.FiberForkJoinScheduler$FiberForkJoinTask.exec1(FiberForkJoinScheduler.java:248)
	at co.paralleluniverse.concurrent.forkjoin.ParkableForkJoinTask.doExec(ParkableForkJoinTask.java:116)
	at co.paralleluniverse.concurrent.forkjoin.ParkableForkJoinTask.exec(ParkableForkJoinTask.java:73)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:261)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:988)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I think this happens because there is a small delay between executing `spawn-fiber` (which submits the task to the executor only) and when the fiber task eventually gets executed by the executor. In the mean time the fiber status has been set to cancelled. This is a perfectly valid situation and should not give rise to an exception.

**Comment by dehubbed** [comment]
I don't claim to understand the code base just yet, but does [this](https://github.com/puniverse/quasar/blob/master/quasar-core/src/main/java/co/paralleluniverse/fibers/Fiber.java#L817) need the same change applied to it? Just checking because it looks the same.

**Comment by pron** [comment]
Yes, good catch!
