### ISSUE TITLE
java.lang.ClassCastException: co.paralleluniverse.asm.tree.InvokeDynamicInsnNode cannot be cast to co.paralleluniverse.asm.tree.MethodInsnNode

### ISSUE THREAD

**Issue by dinix2008** [puniverse/quasar#81]
java.lang.ClassCastException: co.paralleluniverse.asm.tree.InvokeDynamicInsnNode cannot be cast to co.paralleluniverse.asm.tree.MethodInsnNode
	at co.paralleluniverse.fibers.instrument.InstrumentMethod.accept(InstrumentMethod.java:311)
	at co.paralleluniverse.fibers.instrument.InstrumentClass.visitEnd(InstrumentClass.java:241)
	at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
	at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
	at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:107)
	at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:83)
.....

**Comment by circlespainter** [comment]
Which Quasar version are you using, `0.6.2` or a `0.6.3-SNAPSHOT`? Also, could you provide the code that triggers this issue during instrumentation? It makes investigation much easier.

**Comment by dinix2008** [comment]
>Which Quasar version are you using, 0.6.2 or a 0.6.3-SNAPSHOT?

both

>Also, could you provide the code that triggers this issue during instrumentation

clone project https://github.com/dinix2008/quasar-groovy and run 

```bash
$ mvn clean install -Dgroovy.target.indy=true
```

-Dgroovy.target.indy property indicates whether or not to use invokeDynamic in groovy. If you do not use the invokeDynamic support test is performed successfully.

**Comment by circlespainter** [comment]
Can you try with a local `0.6.3-SNAPSHOT` build from this branch https://github.com/puniverse/quasar/tree/fix-81? It seems to work here.

**Comment by dinix2008** [comment]
Thanks! Bug has been fixed
