### ISSUE TITLE
The method Fiber#checkInstrumentation may work incorrectly.

### ISSUE THREAD

**Issue by dinix2008** [puniverse/quasar#82]
In project https://github.com/dinix2008/quasar-groovy i instrument method org.codehaus.groovy.vmplugin.v7.IndyInterface#selectMethod. Using jad I see that the class is annotated @Instrumented and changing the method "selectMetnod". In the test,I check that this method is actually defined as the instrumented using 
```java
SuspendableHelper.isInstrumented(org.codehaus.groovy.vmplugin.v7.IndyInterface.class, "selectMethod");
```
and the test is successful. But fiber with call this method generates an exception 

```java
selectMethodInstrumented(org.codehaus.groovy.quasar.FiberTest)  Time elapsed: 0.7 sec  <<< ERROR!
java.util.concurrent.ExecutionException: co.paralleluniverse.fibers.VerifyInstrumentationException: Uninstrumented methods on the call stack (marked with **): 
	at co.paralleluniverse.fibers.Fiber.checkInstrumentation(Fiber.java:1604)
	at co.paralleluniverse.fibers.Fiber.verifySuspend(Fiber.java:1575)
	at co.paralleluniverse.fibers.Fiber.sleep(Fiber.java:627)
	at co.paralleluniverse.fibers.Fiber.sleep(Fiber.java:619)
	at co.paralleluniverse.strands.Strand.sleep(Unknown Source)
	at org.codehaus.groovy.runtime.DefaultGroovyStaticMethods.sleepImpl(Unknown Source)
	at org.codehaus.groovy.runtime.DefaultGroovyStaticMethods.sleep(Unknown Source)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(Unknown Source) **oops. problem with stacktrace can't be trusted
	at script1425639769084840396098.run(Unknown Source) **oops. problem with stacktrace can't be trusted
	at org.codehaus.groovy.quasar.FiberTest$4.run(Unknown Source) **oops. problem with stacktrace can't be trusted
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(Unknown Source)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(Unknown Source)
	at co.paralleluniverse.fibers.Fiber.run(Fiber.java:1013)
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1008)
	at co.paralleluniverse.fibers.Fiber.get(Fiber.java:1296)
	at co.paralleluniverse.fibers.Fiber.join(Fiber.java:1271)
	at org.codehaus.groovy.quasar.FiberTest.selectMethodInstrumented(FiberTest.java:145)
....
```

To reproduce please clone git@github.com:dinix2008/quasar-groovy.git and run 

```bash
$ mvn clean install -Dgroovy.target.indy=true -Dquasar.version=0.6.3-SNAPSHOT -Dco.paralleluniverse.fibers.verifyInstrumentation=true -Dtest=FiberTest#selectMethodInstrumented
```

**Comment by circlespainter** [comment]
I started looking into it, I see you unpack Groovy and then use AOT instrumentation, anyway the issue appears even when using the agent.
I'll have to look deeper but initial inspection makes me think that in some circumstances the instrumentation verification can report an imprecise stack (the "oops. problem with stacktrace can't be trusted" seems to hint about that), like in this case where there are few elements that could be disturbing (`invokeDynamic`, a dynamically compiled script, Groovy). It could be the case that your method is correctly instrumented indeed but the instrumentation problem lies somewhere else.
Apart from the `checkInstrumentation` correctness, have you been able to fix instrumentation issues and let your test run?

**Comment by dinix2008** [comment]
Thanks! Bug has been fixed
