### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 36

### ISSUE THREAD

**Issue by dinix2008** [puniverse/quasar#83]
```java
Exception in Fiber "fiber-test-10000001" java.lang.ArrayIndexOutOfBoundsException: 36
	at co.paralleluniverse.fibers.Stack.getObject(Stack.java:209)
	at groovy.lang.MetaClassImpl.getMethodWithCaching(Unknown Source)
	at groovy.lang.MetaClassImpl.invokeMethod(Unknown Source)
	at groovy.lang.MetaClassImpl.invokeMethod(Unknown Source)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(Unknown Source)
	at script14261386879211176730158.run(Unknown Source)
	at org.codehaus.groovy.quasar.FiberTest$3.run(Unknown Source)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(Unknown Source)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(Unknown Source)
	at co.paralleluniverse.fibers.Fiber.run(Fiber.java:1013)
        ...
```

To reproduce please clone git@github.com:dinix2008/quasar-groovy.git and run test FiberTest#testClosuresSleep

```bash
$ mvn clean install -Dgroovy.target.indy=true -Dquasar.version=0.6.3-SNAPSHOT -Dco.paralleluniverse.fibers.verifyInstrumentation=true -Dtest=FiberTest#testClosuresSleep
```

**Comment by circlespainter** [comment]
It could be an instrumentation issue triggered by some specific code pattern in `groovy.lang.MetaClassImpl.getMethodWithCaching`. The way to solve the issue here is to isolate that code pattern in the smallest/simplest sample still triggering it, and then see what goes wrong during instrumentation. We'll look into it.
Still you might be more familiar with the Groovy codebase, so if you have any suspicions or even time to build a minimal, self-contained code sample triggering the issue independently of this specific context and of the `groovy.lang.MetaClassImpl.getMethodWithCaching` method, this would help us a lot.

**Comment by circlespainter** [comment]
With latest quasar@master (including source/debug info by default):

~~~
Exception in Fiber "fiber-test-10000001" java.lang.ArrayIndexOutOfBoundsException: 36
	at co.paralleluniverse.fibers.Stack.getObject(Stack.java:209)
	at groovy.lang.MetaClassImpl.getMethodWithCaching(MetaClassImpl.java:1278)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1054)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:215)
	at script14266579813821176730158.run(script14266579813821176730158.groovy:1)
	at org.codehaus.groovy.quasar.FiberTest$3.run(FiberTest.java:79)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:42)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:30)
	at co.paralleluniverse.fibers.Fiber.run(Fiber.java:1013)
~~~

**Comment by circlespainter** [comment]
@dinix2008 I commented out a few `suspendables` (e.g. `groovy.lang.MetaClassImpl.chooseMethod`) that seem to be useful only during method selection (indy bootstrap?) and `selectMethod` should be a method selector too (according to the JavaDoc here https://github.com/groovy/groovy-core/blob/master/src/main/org/codehaus/groovy/vmplugin/v7/IndyInterface.java#L207) but it seems to invoke fiber-enabled sleeps directly instead (see trace that follows), seemingly on behalf of the dynamic script.
Why is that?

~~~
	at org.codehaus.groovy.runtime.DefaultGroovyStaticMethods.sleepImpl(DefaultGroovyStaticMethods.java:133)
	at org.codehaus.groovy.runtime.DefaultGroovyStaticMethods.sleep(DefaultGroovyStaticMethods.java:157)
	at java.lang.invoke.LambdaForm$DMH/1153655111.invokeStaticInit_LJ_V(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$BMH/1716812748.reinvoke(LambdaForm$BMH)
	at java.lang.invoke.LambdaForm$MH/864622439.guardWithCatch(LambdaForm$MH)
	at java.lang.invoke.LambdaForm$reinvoker/254960637.dontInline(LambdaForm$reinvoker)
	at java.lang.invoke.LambdaForm$MH/1478020905.guard(LambdaForm$MH)
	at java.lang.invoke.LambdaForm$reinvoker/254960637.dontInline(LambdaForm$reinvoker)
	at java.lang.invoke.LambdaForm$MH/1478020905.guard(LambdaForm$MH)
	at java.lang.invoke.LambdaForm$reinvoker/254960637.dontInline(LambdaForm$reinvoker)
	at java.lang.invoke.LambdaForm$MH/981738308.guard(LambdaForm$MH)
	at java.lang.invoke.LambdaForm$MH/1945746051.invokeExact_MT(LambdaForm$MH)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:215)
	at java.lang.invoke.LambdaForm$DMH/648627788.invokeStaticInit_L3IL5_L(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$BMH/60434138.reinvoke(LambdaForm$BMH)
	at java.lang.invoke.LambdaForm$MH/1553438171.linkToCallSite(LambdaForm$MH)
	at script14270470042351176730158.run(script14270470042351176730158.groovy:1)
	at org.codehaus.groovy.quasar.FiberTest$3.run(FiberTest.java:79)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:42)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:30)
	at co.paralleluniverse.fibers.Fiber.run(Fiber.java:1013)
~~~

**Comment by circlespainter** [comment]
@dinix2008 Have you had a chance to take a look?

**Comment by circlespainter** [comment]
@dinix2008 Closing for inactivity but you can reopen it.
